// Includes all 28 Indian states and 8 Union Territories for address forms.
export const INDIAN_STATES_AND_UNION_TERRITORIES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const;

// District/city options curated from the supplied India location data.
// A district without listed sub-localities falls back to the district name as its city.
export const STATE_DISTRICTS: Record<string, string[]> = {
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati'],
  'Arunachal Pradesh': ['Itanagar', 'Tawang', 'Ziro'],
  Assam: ['Guwahati', 'Dibrugarh', 'Silchar'],
  Bihar: ['Patna', 'Gaya', 'Bhagalpur'],
  Chhattisgarh: ['Raipur', 'Bhilai', 'Bilaspur'],
  Goa: ['Panaji', 'Margao', 'Vasco da Gama'],
  Gujarat: ['Ahmedabad', 'Surat', 'Vadodara'],
  Haryana: ['Gurugram', 'Faridabad', 'Panipat'],
  'Himachal Pradesh': ['Shimla', 'Dharamshala', 'Manali'],
  Jharkhand: ['Ranchi', 'Jamshedpur', 'Dhanbad'],
  Karnataka: ['Bengaluru', 'Mysuru', 'Mangaluru'],
  Kerala: ['Kochi', 'Thiruvananthapuram', 'Kozhikode'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior'],
  Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Navi Mumbai'],
  Manipur: ['Imphal', 'Thoubal'],
  Meghalaya: ['Shillong', 'Tura'],
  Mizoram: ['Aizawl', 'Lunglei'],
  Nagaland: ['Kohima', 'Dimapur'],
  Odisha: ['Bhubaneswar', 'Cuttack', 'Rourkela'],
  Punjab: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Mohali'],
  Rajasthan: ['Jaipur', 'Jodhpur', 'Udaipur'],
  Sikkim: ['Gangtok', 'Namchi'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
  Telangana: ['Hyderabad', 'Warangal', 'Nizamabad'],
  Tripura: ['Agartala', 'Udaipur'],
  'Uttar Pradesh': ['Lucknow', 'Noida', 'Kanpur', 'Ghaziabad', 'Varanasi'],
  Uttarakhand: ['Dehradun', 'Haridwar', 'Rishikesh'],
  'West Bengal': ['Kolkata', 'Howrah', 'Siliguri'],
  Delhi: ['New Delhi', 'Dwarka', 'Rohini'],
  'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Anantnag'],
  Ladakh: ['Leh', 'Kargil'],
  Chandigarh: ['Chandigarh'],
  Puducherry: ['Puducherry', 'Karaikal'],
};

export const DISTRICT_CITIES: Record<string, string[]> = {
  Gurugram: [
    'DLF Phase 1',
    'DLF Phase 4',
    'Sohna Road',
    'Sector 29',
    'Cyber City',
    'MG Road',
  ],
  Faridabad: ['Sector 15', 'Sector 21', 'Ballabhgarh'],
  Mumbai: ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Colaba', 'Powai'],
  Pune: ['Kothrud', 'Hinjewadi', 'Wakad', 'Viman Nagar', 'Hadapsar'],
  Bengaluru: [
    'Koramangala',
    'Indiranagar',
    'Whitefield',
    'Electronic City',
    'Jayanagar',
  ],
  Chennai: ['T Nagar', 'Anna Nagar', 'Velachery', 'Adyar', 'Mylapore'],
  Hyderabad: [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Madhapur',
    'Hitech City',
  ],
  Ahmedabad: ['Navrangpura', 'Satellite', 'Bodakdev', 'Maninagar'],
  Jaipur: ['Malviya Nagar', 'C-Scheme', 'Vaishali Nagar', 'Mansarovar'],
  Lucknow: ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Indira Nagar'],
  Noida: ['Sector 18', 'Sector 62', 'Sector 50', 'Sector 137'],
  Kolkata: ['Salt Lake', 'Park Street', 'Ballygunge', 'New Town'],
  Bhopal: ['Arera Colony', 'MP Nagar', 'Kolar Road'],
  Chandigarh: ['Sector 17', 'Sector 22', 'Sector 35', 'Sector 43'],
  Mohali: [
    'Phase 1',
    'Phase 3B2',
    'Phase 7',
    'Kharar',
    'Zirakpur',
    'Sector 70',
  ],
  Ludhiana: ['Model Town', 'Sarabha Nagar', 'Civil Lines', 'Dugri'],
  Amritsar: ['Ranjit Avenue', 'Green Avenue', 'Lawrence Road'],
  Delhi: ['Connaught Place', 'Chanakyapuri', 'Karol Bagh', 'Paharganj'],
  'New Delhi': ['Connaught Place', 'Chanakyapuri', 'Karol Bagh', 'Paharganj'],
  Dwarka: [
    'Dwarka Sector 6',
    'Dwarka Sector 12',
    'Dwarka Sector 21',
    'Uttam Nagar',
  ],
};
