const en = {
  translation: {
    guardProfile: {
      role: 'Security Guard',
      empId: 'EMP ID: {{id}}',
      personalInformation: 'Personal Information',
      documents: 'Documents',
      bankDetails: 'Bank Details',
      emergencyContact: 'Emergency Contact',
      settings: 'Settings',
      signOut: 'Sign out',
      profilePhoto: 'Profile photo',
      loadingProfile: 'Loading profile…',
      loadFailed: 'Unable to load your profile.',
      tryAgain: 'Try again',
      comingSoon: 'This section will be available soon.',
      guardId: 'Guard ID',
      assignedSite: 'Assigned site',
      dutyStatus: 'Duty status',
      notAvailable: 'Not available',
      back: 'Go back',
      editProfile: 'Edit profile',
      employmentInformation: 'Employment Information',
      age: 'Age',
      gender: 'Gender',
      genderOptions: {
        male: 'Male',
        female: 'Female',
        other: 'Other',
      },
      cancel: 'Cancel',
      saveChanges: 'Save changes',
      saving: 'Saving…',
      profileUpdated: 'Profile updated',
      profileUpdatedHint: 'Your profile details have been saved.',
      updateFailed: 'Unable to update profile',
      idProof: 'ID Proof',
      securityLicense: 'Security License',
      certifications: 'Certifications',
      verified: 'VERIFIED',
      pending: 'PENDING',
      accountNumber: 'Account Number',
      ifscCode: 'IFSC Code',
      bankName: 'Bank Name',
      contactName: 'Contact Name',
      relationship: 'Relationship',
      contactPhone: 'Contact Phone',
      bankSaved: 'Bank details saved',
      bankSavedHint: 'Your bank details have been saved.',
      emergencySaved: 'Emergency contact saved',
      emergencySavedHint: 'Your emergency contact has been saved.',
      validation: {
        nameRequired: 'Please enter your full name.',
        emailRequired: 'Please enter your email address.',
        emailInvalid: 'Please enter a valid email address.',
        mobileInvalid: 'Please enter a valid 10-digit mobile number.',
        ageInvalid: 'Age must be between 18 and 65.',
        accountNumberInvalid:
          'Please enter a valid bank account number (9 to 18 digits).',
        ifscInvalid: 'Please enter a valid 11-character IFSC code.',
        bankNameRequired: 'Please enter your bank name.',
        contactNameRequired: 'Please enter the contact name.',
        relationshipRequired: 'Please enter the relationship.',
        contactPhoneInvalid:
          'Please enter a valid 10-digit contact phone number.',
      },
      documentsEmpty: 'No documents yet',
      documentsEmptyHint:
        'Your ID proofs and certifications will appear here once uploaded.',
      bankEmpty: 'No bank details yet',
      bankEmptyHint:
        'Add your bank account details to receive salary payments.',
      emergencyEmpty: 'No emergency contact yet',
      emergencyEmptyHint:
        'Add a contact to be reached in case of an emergency.',
      settingsEmpty: 'Nothing to configure',
      settingsEmptyHint: 'App preferences and settings will appear here.',
    },
    clientAgency: {
      guardsOnSite: 'GUARDS ON SITE',
      loadingGuards: 'Loading assigned guards…',
      loadFailed: 'Unable to load assigned guards.',
      rateAgency: 'Rate Your Agency',
      feedbackPlaceholder: 'Share your experience with this agency…',
      guardFeedbackPlaceholder: 'Share feedback about this guard…',
      saveRating: 'Save rating',
      ratingSaved: 'Rating saved',
      thankYou: 'Thank you for your feedback.',
      unableToRate: 'Unable to save rating',
      noGuards: 'No guards assigned yet',
      noGuardsHint:
        'Assigned guards will appear here once the agency completes the assignment.',
      onSite: 'ON SITE',
      overallRating: 'Overall rating',
      rate: 'Rate',
    },
    coverageManagement: {
      requests: 'Client Requests',
      loading: 'Loading client requests…',
      loadFailed: 'Unable to load client requests.',
      noRequests: 'No client requests',
      noRequestsHint: 'New coverage requests will appear here.',
      requestDetails: 'Request details',
      client: 'Client',
      event: 'Site or event',
      location: 'Location',
      guardsNeeded: 'Guards needed',
      guardsCount: '{{count}} guard requested',
      guardsCount_other: '{{count}} guards requested',
      notes: 'Notes',
      noNotes: 'No notes provided',
      status: 'Status',
      assignGuards: 'Assign guards',
      assignLimit: 'Select up to {{count}} available guards.',
      selectGuardFirst: 'Select at least one available guard.',
      noAvailableGuards: 'No off-duty guards are currently available.',
      approve: 'Approve',
      reject: 'Reject',
      assignSelected: 'Assign selected guards',
      markCompleted: 'Mark completed',
      requestUpdated: 'Request updated',
      requestUpdatedHint: 'The client request status has been saved.',
      unableToUpdate: 'Unable to update request',
      statuses: {
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        assigned: 'Assigned',
        completed: 'Completed',
      },
    },
    addGuardForm: {
      title: 'Add Guard',
      fullName: 'Full name',
      mobileNumber: 'Mobile number',
      email: 'Email',
      password: 'Password',
      joiningDate: 'Joining date',
      address: 'Address (optional)',
      age: 'Age (optional)',
      gender: 'Gender (optional)',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      site: 'Initial site assignment',
      unassigned: 'Unassigned',
      loadingSites: 'Loading sites…',
      siteError:
        'Sites could not be loaded. You can add an unassigned guard or reopen the form to retry.',
      coveragePlan: 'Coverage plan',
      day_shift: 'Day Shift',
      night_watch: 'Night Watch',
      '24x7': '24×7 Coverage',
      shiftHours: 'Shift duration',
      hours: 'hours',
      startTime: 'Start time',
      endTime: 'End time',
      endHint:
        'End time is calculated from the selected shift duration, including overnight shifts.',
      coverageHint:
        '24×7 coverage uses rotating shifts; no individual shift duration is assigned here.',
      basicSalary: 'Basic salary (optional)',
      allowances: 'Allowances (optional)',
      requiredHint: 'Fields marked * are required.',
      requiredError: 'Complete all required fields.',
      contactError:
        'Enter a valid 10-digit Indian mobile, email and password of at least 6 characters.',
      dateError: 'Enter a valid joining date as YYYY-MM-DD.',
      ageError: 'Age must be a whole number between 18 and 65.',
      salaryError:
        'Enter a non-negative salary and allowances with up to two decimal places.',
      success: 'Guard added successfully.',
      failure: 'Could not add guard. Please try again.',
      saving: 'Saving…',
      search: 'Search options',
      noResults: 'No matching options.',
      close: 'Close',
    },
    common: {
      next: 'Next',
      back: 'Back',
      continue: 'Continue',
      getStarted: 'Get Started',
      skip: 'Skip', // NEW
    },

    auth: {
      welcomeBack: 'Welcome Back',
      login: 'Log In',
      createAccount: 'Create Account',
      forgotPassword: 'Forgot Password?',
      loginSubtitle: 'Please log in to continue',
      emailAddress: 'Email Address',
      password: 'Password',
      enterPassword: 'Enter your password',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      loggingIn: 'Logging in...',
      orContinueWith: 'Or continue with',
      noAccount: "Don't have an account?",
      signUp: 'Sign up',
      invalidDetails: 'Invalid details',
      enterLinkedEmail: 'Enter the email address linked to your account.',
      invalidPassword: 'Invalid password',
      loginFailed: 'Login failed',
      tryAgain: 'Please try again.',
      createSubtitle: 'Fill in your details to get started',
      fullName: 'Full Name',
      mobileNumber: 'Mobile Number',
      confirmPassword: 'Confirm Password',
      exampleName: 'e.g. Akash Singh',
      alreadyAccount: 'Already have an account?',
      invalidName: 'Invalid name',
      enterFullName: 'Enter your full name.',
      invalidEmail: 'Invalid email address',
      enterValidEmail: 'Enter a valid email address.',
      passwordsMismatch: 'Passwords do not match',
      passwordsMismatchMessage: 'Password and confirmation must match.',
      accountFailed: 'Could not create account',
      backToSuperAdmin: 'Back to Super Admin',
      goBack: 'Go back',
      forgotTitle: 'Forgot Password',
      emailOrMobile: 'Email or Mobile Number',
      rememberPassword: 'Remember your password?',
      sendOtp: 'Send OTP',
      sending: 'Sending...',
      forgotSubtitle: 'Enter your registered email or mobile number',
      verifyMobile: 'Verify Mobile Number',
      verifyOtp: 'Verify OTP',
      enterCodeSent: 'Enter the 6-digit code sent to',
      didNotReceive: "Didn't receive OTP?",
      resendOtp: 'Resend OTP',
      resendIn: 'in 00:30',
      verifyContinue: 'Verify & Continue',
      verifying: 'Verifying...',
      couldNotResend: 'Could not resend OTP',
      newPassword: 'New Password',
      enterNewPassword: 'Enter new password',
      confirmNewPassword: 'Confirm new password',
      newPasswordSubtitle: 'Enter your new password',
      resetPassword: 'Reset Password',
      resetting: 'Resetting...',
      passwordUpdated: 'Password Updated Successfully!',
      passwordUpdatedMessage:
        'Your password has been updated. You can now log in with your new password.',
      goToLogin: 'Go to Login',
      invalidMobile: 'Invalid mobile number',
      enterValidMobile: 'Enter a valid 10-digit Indian mobile number.',
      confirmMustMatch: 'Confirm password must match the password.',
      accountType: 'Account type',
      chooseAccountType: 'Choose your account type...',
      agency: 'Agency',
      client: 'Client',
      agencyDescription: 'Manage guards &\nsecurity services',
      clientDescription: 'Hire & manage\nsecurity services',
      creatingAccount: 'Creating account...',
      enterValidIdentifier: 'Enter a valid email address or mobile number.',
      couldNotSendOtp: 'Could not send OTP',
      identifierPlaceholder: 'you@example.com or +91 98765 43210',
      passwordChanged: 'Your password has been changed successfully.',
      invalidOtp: 'Invalid OTP',
      completeOtp: 'Enter the complete 6-digit verification code.',
      verificationFailed: 'Verification failed',
      identifierFallback: 'your email or mobile number',
      otpDigit: 'OTP digit {{number}}',
      mobileOtpDigit: 'Mobile verification digit {{number}}',
    },
    onboarding: {
      step1: {
        title: 'Secure People,\nSecure Places.',
        subtitle:
          'Professional security management made simple, reliable and efficient.',
      },
      step2: {
        title: 'Manage Anytime, Anywhere',
        subtitle:
          'Stay connected with your security operations wherever you are.',
      },
      step3: {
        title: 'Stay Alert, Respond Faster.',
        subtitle: 'Receive updates and respond to incidents without delay.',
      },
    },
    superAdmin: {
      agencies: 'Agencies',
      approvals: 'Approvals',
      liveStatus: 'Live Status',
      profile: 'Profile',
      addAgency: 'Add New Agency',
      searchAgencies: 'Search agencies by name',
      active: 'Active',
      inactive: 'Non-active',
      guards: 'Guards',
      clients: 'Clients',
      loadingAgencies: 'Loading agencies',
      unableAgencies: 'Unable to load agencies.',
      noMatching: 'No matching agencies',
      noInactive: 'No non-active agencies',
      noActive: 'No active agencies yet',
      searchHint: 'Try another agency name or switch the status filter.',
      approvalHint: 'Approved agencies appear here after Super Admin review.',
      networkTitle: 'Your network at a glance',
      liveUnavailable: 'Live reporting is not available yet.',
      agencyApprovals: 'Agency approvals',
      refreshRequests: 'Refresh requests',
      noPending: 'No agencies awaiting approval.',
      approve: 'Approve',
      reject: 'Reject',
      notifications: 'Notifications',
      markAllRead: 'Mark all read',
      reviewApprovals: 'Review agency approvals',
      loadingNotifications: 'Loading notifications…',
      tryAgain: 'Try again',
      noNotifications: 'No notifications yet',
      deleteNotification: 'Delete notification?',
      deleteNotificationMessage: 'This notification will be removed.',
      delete: 'Delete',
      cancel: 'Cancel',
      loadingProfile: 'Loading profile…',
      profilePhoto: 'Profile photo',
      photoSoon: 'Profile photo upload will be available soon.',
      yourAccount: 'YOUR ACCOUNT',
      accountId: 'Account ID: {{id}}',
      fullName: 'Full name',
      email: 'Email',
      mobileNumber: 'Mobile number',
      saving: 'Saving…',
      saveChanges: 'Save changes',
      signOut: 'Sign out',
      profileUpdated: 'Profile updated',
      changesSaved: 'Your changes have been saved.',
      fullNameRequired: 'Full name required',
      enterFullName: 'Enter the Super Admin’s full name.',
      invalidEmail: 'Invalid email',
      enterEmail: 'Enter a valid email address.',
      invalidPhone: 'Invalid phone number',
      enterPhone: 'Enter a valid 10-digit Indian mobile number.',
      editAgency: 'Edit Agency',
      manageAgency: 'Manage Agency account details',
      agencyDetails: 'AGENCY DETAILS',
      accountDetails: 'ACCOUNT DETAILS',
      businessDetails: 'BUSINESS DETAILS',
      address: 'Address',
      status: 'Status',
      leavePassword: 'Leave blank to keep current',
      removeAgency: 'Remove agency',
      agencyUpdated: 'Agency updated',
      agencySaved: 'The Agency details have been saved.',
      loadingLocations: 'Loading locations…',
      closeEditor: 'Close Agency editor',
    },
    details: {
      agencyTitle: 'Agency Details',
      agencySubtitle: 'Tell us about your agency',
      agencyName: 'Agency / Company Name',
      enterAgencyName: 'Enter agency name',
      businessType: 'Business Type',
      gstNumber: 'GST Number (Optional)',
      enterGst: 'Enter GST number',
      officeAddress: 'Office Address',
      enterOfficeAddress: 'Enter office address',
      clientTitle: 'Client Details',
      clientSubtitle: 'Tell us about your organization',
      companyName: 'Company / Organization Name',
      enterCompanyName: 'Enter company name',
      siteName: 'Site / Property Name',
      enterSiteName: 'Enter site/property name',
      siteAddress: 'Site Address',
      enterSiteAddress: 'Enter site address',
      enterCity: 'Enter city',
      selectState: 'Select state',
      enterPincode: 'Enter pincode',
      loadingLocations: 'Loading locations…',
      closeLocations: 'Close location options',
      agencyNameRequired: 'Agency name required',
      enterAgencyCompany: 'Enter your agency or company name.',
      businessRequired: 'Business type required',
      selectBusiness: 'Select your business type.',
      officeRequired: 'Office address required',
      enterOffice: 'Enter your office address.',
      cityRequired: 'City required',
      enterYourCity: 'Enter your city.',
      stateRequired: 'State required',
      selectStateTerritory: 'Select your state or Union Territory.',
      districtRequired: 'District required',
      selectDistrict: 'Select your district.',
      invalidPincode: 'Invalid pincode',
      enterValidPincode: 'Enter a valid 6-digit pincode.',
      siteNameRequired: 'Site name required',
      enterProperty: 'Enter your site or property name.',
      siteAddressRequired: 'Site address required',
      enterAddress: 'Enter the site address.',
    },
    client: {
      home: 'Home',
      request: 'Request',
      invoices: 'Invoices',
      alerts: 'Alerts',
      profile: 'Profile',
      portal: 'Client Portal',
      loading: 'Loading client details…',
      loadFailed: 'Unable to load client details.',
      yourAgencies: 'YOUR AGENCIES',
      noAgency: 'No agency assigned',
      noAgencyHint: 'Your assigned security agency will appear here.',
      coveragePlan: 'COVERAGE PLAN',
      noCoverage: 'No coverage plan',
      noCoverageHint:
        'Coverage details will appear once an agency is assigned.',
      requestCoverage: 'Request security coverage',
      requestHint: 'Coverage request functionality will appear here.',
      noInvoices: 'No invoices',
      noInvoicesHint: 'Your invoices will appear here when available.',
      noAlerts: 'No alerts',
      noAlertsHint: 'Security and account alerts will appear here.',
      noAgencyYet: 'No Agency Yet',
      noAgencyYetHint:
        "You haven't hired an agency yet. Use the Request tab to find and send a coverage request.",
      helpfulInformation: 'HELPFUL INFORMATION',
      howItWorks: 'How it works?',
      howItWorksHint: 'Learn how to request and manage coverage',
      whyHireAgency: 'Why hire an agency?',
      whyHireAgencyHint: 'Get professional and reliable security',
      needHelp: 'Need help?',
      needHelpHint: 'Contact our support team',
      securityQuote: '“Safer spaces, stronger business.”',
      welcomeBack: 'Welcome Back!',
      securityOverview: "Here's an overview of your security coverage.",
      securityPartner: 'Your security partner',
      activeCoverage: 'ACTIVE COVERAGE',
      guardsAssigned: '{{count}} guard assigned',
      guardsAssigned_other: '{{count}} guards assigned',
      active: 'Active',
    },
    clientInfo: {
      back: 'Back',
      howItWorksIntro: 'Requesting professional security coverage is simple.',
      whyHireIntro:
        'The benefits of working with a professional security agency.',
      chooseLocation: 'Choose your location',
      chooseLocationBody:
        'Select the state, district, city, and exact site where coverage is needed.',
      selectAgency: 'Review and select an agency',
      selectAgencyBody:
        'Compare approved agencies available in your district and review their details.',
      sendRequest: 'Send your request',
      sendRequestBody:
        'Enter the guards needed and your requirements, then submit the request.',
      trackCoverage: 'Track your coverage',
      trackCoverageBody:
        'Follow the request status and view active coverage from your Home screen.',
      verifiedSecurity: 'Verified security providers',
      verifiedSecurityBody:
        'Choose from agencies reviewed and approved for the platform.',
      trainedGuards: 'Professionally managed guards',
      trainedGuardsBody:
        'Agencies manage guard assignments, shifts, and site requirements.',
      reliableCoverage: 'Reliable coverage',
      reliableCoverageBody:
        'Request the number of guards your site or event requires.',
      clearRecords: 'Clear digital records',
      clearRecordsBody:
        'Keep requests, coverage information, invoices, and alerts organized.',
      requestNote: 'You can begin at any time from the Request tab.',
      partnerNote:
        'Review agency details before confirming your coverage request.',
      supportSubject: 'Sentry Security App Support',
      emailUnavailable:
        'No email application is available. Contact helpdesk@gmail.com.',
    },
    coverageRequest: {
      location: 'YOUR LOCATION',
      eventName: 'Event name',
      eventPlaceholder: 'Enter event name',
      siteLocation: 'Site or event location',
      sitePlaceholder: 'e.g. East Wing entrance',
      guardsNeeded: 'Guards needed',
      notes: 'Notes',
      notesPlaceholder: 'Dates, shift timing, special requirements…',
      send: 'Send Request',
      sending: 'Sending…',
      myRequests: 'MY REQUESTS',
      none: 'No coverage requests yet.',
      required: 'Complete all required fields.',
      sentTitle: 'Request sent',
      sentMessage: 'Your coverage request has been submitted.',
      sendFailed: 'Could not send request.',
      loadFailed: 'Could not load requests.',
      locationFailed: 'Could not load locations.',
      selectStateFirst: 'Select a state first.',
      selectDistrictFirst: 'Select a district first.',
      agenciesInArea: 'AGENCIES IN YOUR AREA',
      noAgenciesInArea:
        'No agencies found in this district yet — try a nearby district.',
      agenciesFailed: 'Could not load agencies in this district.',
      available: 'Available',
      selectAgency: 'Select',
      changeAgency: 'Change',
      agencyDetails: 'Agency details',
      agencyDetailsFailed: 'Could not load agency details.',
      loadingAgencyDetails: 'Loading agency details…',
      serviceArea: 'Service area',
      selectThisAgency: 'Select Agency',
      status: {
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        assigned: 'Assigned',
        completed: 'Completed',
        cancelled: 'Cancelled',
      },
    },
    dashboard: {
      noNotificationsHint: 'Your notifications will appear here.',
      dashboard: 'Dashboard',
      overview: 'Overview',
      guard: 'Guard',
      sites: 'Sites',
      incidents: 'Incidents',
      plan: 'Plan',
      profile: 'Profile',
      quickSummary: 'QUICK SUMMARY',
      today: 'Today',
      guardsOnDuty: 'Guards on duty',
      activeSites: 'Active sites',
      openIncidents: 'Open incidents',
      unassignedGuards: 'Unassigned guards',
      viewDetails: 'View details',
      payrollSummary: 'PAYROLL SUMMARY',
      invoices: 'INVOICES',
      clientReviews: 'CLIENT REVIEWS',
      quickActions: 'QUICK ACTIONS',
      liveStatus: 'LIVE STATUS',
      viewAll: 'View All',
      onDuty: 'On Duty',
      addGuard: '+ Guard',
      addSite: '+ Add Site',
      incident: 'Incident',
      fileIncident: 'File Incident',
      searchSites: 'Search sites...',
      filter: 'Filter',
      loadingSites: 'Loading sites...',
      noSites: 'No sites found.',
      loadingIncidents: 'Loading incidents...',
      noIncidents: 'No incidents found.',
      unableToLoadSites: 'Unable to load sites.',
      unableToLoadIncidents: 'Unable to load incidents.',
      site: 'Site',
      selectSite: 'Select Site',
      selectInitialSite: 'Select initial site',
      selectJoiningDate: 'Select joining date',
      year: 'Year',
      month: 'Month',
      date: 'Date',
      done: 'Done',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      previousMonth: 'Previous month',
      nextMonth: 'Next month',
      editGuard: 'Edit Guard',
      guardUpdated: 'Guard details updated successfully.',
      newGuardPassword: 'New password (optional)',
      leavePasswordBlank: 'Leave blank to keep current password',
      removeGuard: 'Remove Guard',
      removeGuardConfirmation:
        'Remove this guard? Their login will stop working. This cannot be undone.',
      cancel: 'Cancel',
      all: 'All',
      severity: 'Severity',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      notes: 'Notes',
      describeIncident: 'Describe what happened...',
      uploadPhotos: 'Upload Photos',
      optional: '(Optional)',
      addPhotos: 'Add Photos',
      maxPhotos: 'Max 5 images, up to 10MB each',
      filing: 'Filing...',
      incidentFiled: 'Incident Filed Successfully',
      incidentRecorded: 'Your incident has been recorded and will be reviewed.',
      siteName: 'Site name',
      address: 'Address',
      enterSiteName: 'Enter site name',
      enterCompleteAddress: 'Enter complete address',
      startTyping: 'Start typing for suggestions',
      locationGps: 'Location (GPS)',
      noGps: 'No GPS location captured',
      useCurrentLocation: 'Use current location',
      coveragePlan: 'Coverage Plan',
      dayShift: 'Day Shift',
      nightWatch: 'Night Watch',
      coverage24x7: '24×7 Coverage',
      startTime: 'Start time',
      endTime: 'End time',
      saveSite: 'Save site',
      saving: 'Saving...',
      addressNotProvided: 'Address not provided',
      guardDataUnavailable: 'Guard data unavailable',
      notSet: 'Not set',
      notScheduled: 'Not scheduled',
      myProfile: 'My Profile',
      settings: 'Settings',
      language: 'Language',
      appearance: 'Appearance',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      logOut: 'Log Out',
      english: 'English',
      hindi: 'Hindi',
      punjabi: 'Punjabi',
      missingDetails: 'Missing details',
      selectSiteAndDescribe: 'Select a site and describe the incident.',
      siteAndAddressRequired: 'Site name and address are required.',
      couldNotFile: 'Could not file incident',
      couldNotLoadSites: 'Could not load sites',
      tryAgain: 'Please try again.',
      photoUploadSoon: 'Photo upload will be connected to storage next.',
      gpsSoon: 'GPS location support will be added next.',
      close: 'Close',
      tapGuardDetails: 'Tap a guard to view or edit their details',
      loadingGuards: 'Loading guards...',
      noGuardsOnDuty: 'No guards are currently on duty.',
      unableToLoadGuards: 'Unable to load guards.',
      unassignedSite: 'Unassigned site',
      live: 'Live',
      noLocationYet: 'No location yet',
      tapSiteManage: 'Tap a site to manage it in the Sites tab',
      active: 'ACTIVE',
      guardCount: '{{count}} guards',
      agencyAdmin: 'Agency Admin',
      accountDetails: 'Account details',
      yourAccount: 'YOUR ACCOUNT',
      fullName: 'Full Name',
      mobileNumber: 'Mobile Number',
      emailAddress: 'Email Address',
      state: 'State',
      district: 'District',
      city: 'City',
      pincode: 'Pincode',
      saveChanges: 'Save changes',
      signOut: 'Sign out',
      profilePhoto: 'Profile photo',
      loadingProfile: 'Loading profile...',
      profileRequired: 'Complete all required account fields.',
      changesSaved: 'Your changes have been saved.',
      offlineAddressHint: 'Address suggestions are unavailable offline.',
      rotateCoverage: 'Guards rotate across shifts to cover all 24 hours.',
      selectedPlan: 'The selected coverage plan will be used for this site.',
      getDirections: 'Get directions',
      directionsUnavailable:
        'Directions will be available when map integration is connected.',
      removeSite: 'Remove site',
      removeSiteConfirm:
        'Remove this site? Existing guard assignments may be affected.',
      siteUpdated: 'Site details have been updated.',
      siteUpdateFailed: 'Site details could not be updated.',
      siteRemoved: 'The site has been removed.',
      siteRemoveFailed: 'The site could not be removed.',
      siteUpdateUnavailable:
        'Site editing and removal need backend update/delete endpoints before changes can be saved.',
      searchGuards: 'Search guards by name, ID, or site',
      offDuty: 'Off Duty',
      noGuardsFound: 'No guards found.',
      callGuard: 'Call guard',
      guardAddUnavailable: 'The Add Guard form will be connected next.',
      noMatchingLocations: 'No matching locations found.',
      planTitle: 'Plan / Billing',
    },
    guard: {
      tabs: {
        duty: 'Duty',
        schedule: 'Schedule',
        patrol: 'Patrol',
        report: 'Report',
        profile: 'Profile',
      },
      common: {
        guardFallback: 'Guard',
        badgeId: 'Badge ID {{id}}',
        closeProfileMenu: 'Close profile menu',
        featureSoon: 'This guard feature will be available soon.',
        tryAgain: 'Please try again.',
      },
      duty: {
        scheduleNotSet: 'Schedule not set',
        loadFailed: 'Unable to load your duty details.',
        updateFailed: 'Unable to update duty',
        loading: 'Loading duty dashboard…',
        clockIn: 'Clock in',
        clockOut: 'Clock out',
        onDuty: 'ON DUTY',
        offDuty: 'OFF DUTY',
        updating: 'Updating…',
        tapToClockIn: 'Tap to clock in',
        tapToClockOut: 'Tap to clock out',
        statusActive: 'Your duty status is active',
        statusAvailable: 'Your agency will see you as available',
        currentAssignment: 'CURRENT ASSIGNMENT',
        radioContact: 'RADIO CONTACT',
        photoLogTitle: "TODAY'S PHOTO LOG",
        assignmentDetails: 'Assignment details',
        callControlRoom: 'Call control room',
        photoLog: 'Photo log',
        noSiteAssigned: 'No site assigned',
        noActiveSite: 'No active site assigned',
        active: 'ACTIVE',
        assigned: 'ASSIGNED',
        controlRoom: 'Control room support',
        channel: 'Channel 1 · 24×7 Support',
        photoEmpty: 'Today’s photo log is empty',
        photoEmptyHint: 'Capture site photos during your shift',
        salaryTitle: 'SALARY',
        salaryRow: 'Salary & payslips',
        salaryCaption: 'View history and advances',
      },
      patrol: {
        loadFailed: 'Unable to load patrol details.',
        loading: 'Loading patrol dashboard…',
        completedTitle: 'Patrol completed',
        completedBody: 'All checkpoints have been recorded successfully.',
        updateFailed: 'Unable to update patrol',
        updating: 'Updating patrol…',
        scanCheckpoint: 'Scan Checkpoint',
        startPatrol: 'Start Patrol',
        scanNext: 'Scan next checkpoint',
        startAction: 'Start patrol',
        recordNext: 'Record the next patrol checkpoint',
        beginRoute: 'Begin your assigned checkpoint route',
        noCheckpoints: 'No checkpoints assigned',
        progress: 'PATROL PROGRESS',
        completedCount: '{{scanned}}/{{total}} completed',
        nextCheckpoint: 'NEXT CHECKPOINT',
        nextCheckpointHint: 'Next checkpoint in your route',
        recentScans: 'RECENT SCANS',
        noScansYet: 'No checkpoints scanned yet today.',
        checkpointList: 'CHECKPOINT LIST',
        checkpointListWithSite: 'CHECKPOINT LIST — {{site}}',
        checkpointCount: '{{count}} checkpoints',
        allScanned: 'All checkpoints scanned',
        roundCompletedTitle: 'Patrol round completed',
        roundCompletedBody: 'Thanks — the full route is recorded.',
      },
      report: {
        severityLow: 'Low',
        severityMedium: 'Medium',
        severityHigh: 'High',
        describeTitle: 'Describe the incident',
        describeBody:
          'Add the incident, location, and action taken before submitting.',
        submittedTitle: 'Report submitted',
        submittedBody: 'Your agency has been notified about this incident.',
        submitFailed: 'Unable to submit report',
        reportDetails: 'REPORT DETAILS',
        severity: 'Severity',
        whatHappened: 'What happened',
        notesPlaceholder: 'Describe the incident, location, and action taken…',
        incidentDetails: 'Incident details',
        attachments: 'Attachments',
        photoTitle: 'Photo attachment',
        photoBody:
          'Photo attachment will be enabled when the app camera or gallery picker is connected.',
        attachPhoto: 'Attach photo',
        submitReport: 'Submit Report',
        submitting: 'Submitting…',
      },
      salary: {
        headerTitle: 'Salary',
        totalSalary: 'Total Salary',
        pending: 'PENDING',
        verified: 'VERIFIED',
        basicSalary: 'Basic Salary',
        overtime: 'Overtime',
        allowances: 'Allowances',
        deductions: 'Deductions',
        netSalary: 'Net Salary',
        downloadPayslip: 'Download Payslip',
        payslipSoon: 'Payslip download will be available soon.',
        history: 'SALARY HISTORY',
        advanceHistory: 'ADVANCE & DEDUCTION HISTORY',
        noAdvances: 'No outstanding advances.',
        loading: 'Loading salary details…',
        loadFailed: 'Unable to load salary details.',
        retry: 'Try again',
      },
    },
    plan: {
      title: 'Plan / Billing',
      currentPlan: 'CURRENT PLAN',
      guards: 'Guards',
      sites: 'Sites',
      limitReached: 'Limit reached',
      monthlyBilling: 'Monthly billing',
      loading: 'Loading plan...',
      loadingPlans: 'Loading plans...',
      loadFailed: 'Unable to load plan information.',
      retry: 'Try again',
      switchFailed: 'Unable to switch plan.',
      paymentMethod: 'PAYMENT METHOD',
      noPaymentMethod: 'No payment method added',
      addPaymentMethod: 'Add Payment Method',
      paymentComingSoon:
        'Payment method management is not available from the API yet.',
      comparePlans: 'COMPARE PLANS',
      noPlans: 'No plans available.',
      currentPlanLabel: 'Current plan',
      billingHistory: 'PLATFORM BILLING HISTORY',
      billingUnavailable: 'Billing history is not available from the API yet.',
      switched: 'Switched to {{name}}.',
      renewsOn: 'Renews {{date}} · Monthly billing',
      planLimits: '{{guards}} Guards · {{sites}} Sites',
      switchTo: 'Switch to {{name}}',
    },
    invoice: {
      sendInvoice: 'SEND INVOICE',
      invoicesSent: 'INVOICES SENT',
      selectClient: 'Select Client',
      amount: 'Amount',
      amountPlaceholder: 'Enter amount',
      description: 'Description',
      descriptionPlaceholder: 'Enter description',
      dueDate: 'Due Date',
      dueDatePlaceholder: 'dd/mm/yyyy',
      selectDueDate: 'Select due date',
      send: 'Send Invoice',
      sending: 'Sending…',
      required: 'Select a client, amount, and due date.',
      invalidAmount: 'Enter an amount greater than zero.',
      sent: 'Invoice sent to {{client}}.',
      sendFailed: 'Could not send invoice.',
      loadingClients: 'Loading clients...',
      noClients: 'No clients available yet.',
      noClientsHint: 'Clients appear here once coverage requests come in.',
      noInvoices: 'No invoices sent yet.',
      pending: 'PENDING',
      paid: 'PAID',
      guardsAssigned: 'Guards assigned',
      totalSalary: 'Total salary',
      noGuards: 'No guards assigned to this client site yet.',
      addOn: 'Add on',
      add1000: '+1000',
      add2000: '+2000',
      addCustom: '+Custom',
      customAddOn: 'Custom add-on',
      apply: 'Apply',
      removeAddOn: 'Remove add-on',
    },
  },
};

export default en;
