const en = {
  translation: {
    common: {
      next: 'Next',
      back: 'Back',
      continue: 'Continue',
      getStarted: 'Get Started',
      skip: 'Skip', // NEW
    },

    onboarding: {
      // NEW
      step1: {
        title: 'Secure People,\nSecure Places.',
        subtitle:
          'Professional security management made simple, reliable and efficient.',
      },
    },

    auth: {
      welcomeBack: 'Welcome Back',
      login: 'Log In',
      createAccount: 'Create Account',
      forgotPassword: 'Forgot Password?',
    },
    dashboard: {
      overview: 'Overview',
      guard: 'Guard',
      sites: 'Sites',
      incidents: 'Incidents',
      plan: 'Plan',
      profile: 'Profile',
      quickSummary: 'QUICK SUMMARY',
      today: 'Today',
      guardsOnDuty: 'Guards on duty',
      activeSites: 'Active sites',
      openIncidents: 'Open incidents',
      unassignedGuards: 'Unassigned guards',
      viewDetails: 'View details',
      payrollSummary: 'PAYROLL SUMMARY',
      invoices: 'INVOICES',
      clientReviews: 'CLIENT REVIEWS',
      quickActions: 'QUICK ACTIONS',
      liveStatus: 'LIVE STATUS',
      viewAll: 'View All',
      onDuty: 'On Duty',
      addGuard: '+ Guard',
      addSite: '+ Add Site',
      incident: 'Incident',
      fileIncident: 'File Incident',
      searchSites: 'Search sites...',
      filter: 'Filter',
      loadingSites: 'Loading sites...',
      noSites: 'No sites found.',
      loadingIncidents: 'Loading incidents...',
      noIncidents: 'No incidents found.',
      unableToLoadSites: 'Unable to load sites.',
      unableToLoadIncidents: 'Unable to load incidents.',
      site: 'Site',
      selectSite: 'Select Site',
      all: 'All',
      severity: 'Severity',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      notes: 'Notes',
      describeIncident: 'Describe what happened...',
      uploadPhotos: 'Upload Photos',
      optional: '(Optional)',
      addPhotos: 'Add Photos',
      maxPhotos: 'Max 5 images, up to 10MB each',
      filing: 'Filing...',
      incidentFiled: 'Incident Filed Successfully',
      incidentRecorded: 'Your incident has been recorded and will be reviewed.',
      siteName: 'Site name',
      address: 'Address',
      enterSiteName: 'Enter site name',
      enterCompleteAddress: 'Enter complete address',
      startTyping: 'Start typing for suggestions',
      locationGps: 'Location (GPS)',
      noGps: 'No GPS location captured',
      useCurrentLocation: 'Use current location',
      coveragePlan: 'Coverage Plan',
      dayShift: 'Day Shift',
      nightWatch: 'Night Watch',
      coverage24x7: '24×7 Coverage',
      startTime: 'Start time',
      endTime: 'End time',
      saveSite: 'Save site',
      saving: 'Saving...',
      addressNotProvided: 'Address not provided',
      guardDataUnavailable: 'Guard data unavailable',
      notSet: 'Not set',
      notScheduled: 'Not scheduled',
      myProfile: 'My Profile',
      settings: 'Settings',
      language: 'Language',
      appearance: 'Appearance',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      logOut: 'Log Out',
      english: 'English',
      hindi: 'Hindi',
      punjabi: 'Punjabi',
      missingDetails: 'Missing details',
      selectSiteAndDescribe: 'Select a site and describe the incident.',
      siteAndAddressRequired: 'Site name and address are required.',
      couldNotFile: 'Could not file incident',
      couldNotLoadSites: 'Could not load sites',
      tryAgain: 'Please try again.',
      photoUploadSoon: 'Photo upload will be connected to storage next.',
      gpsSoon: 'GPS location support will be added next.',
      close: 'Close',
      tapGuardDetails: 'Tap a guard to view or edit their details',
      loadingGuards: 'Loading guards...',
      noGuardsOnDuty: 'No guards are currently on duty.',
      unableToLoadGuards: 'Unable to load guards.',
      unassignedSite: 'Unassigned site',
      live: 'Live',
      noLocationYet: 'No location yet',
      tapSiteManage: 'Tap a site to manage it in the Sites tab',
      active: 'ACTIVE',
      guardCount: '{{count}} guards',
      agencyAdmin: 'Agency Admin',
      accountDetails: 'Account details',
      yourAccount: 'YOUR ACCOUNT',
      fullName: 'Full Name',
      mobileNumber: 'Mobile Number',
      emailAddress: 'Email Address',
      state: 'State',
      district: 'District',
      city: 'City',
      pincode: 'Pincode',
      saveChanges: 'Save changes',
      signOut: 'Sign out',
      profilePhoto: 'Profile photo',
      loadingProfile: 'Loading profile...',
      profileRequired: 'Complete all required account fields.',
      changesSaved: 'Your changes have been saved.',
      offlineAddressHint: 'Address suggestions are unavailable offline.',
      rotateCoverage: 'Guards rotate across shifts to cover all 24 hours.',
      selectedPlan: 'The selected coverage plan will be used for this site.',
      getDirections: 'Get directions',
      directionsUnavailable:
        'Directions will be available when map integration is connected.',
      removeSite: 'Remove site',
      siteUpdateUnavailable:
        'Site editing and removal need backend update/delete endpoints before changes can be saved.',
      searchGuards: 'Search guards by name, ID, or site',
      offDuty: 'Off Duty',
      noGuardsFound: 'No guards found.',
      callGuard: 'Call guard',
      guardAddUnavailable: 'The Add Guard form will be connected next.',
    },
  },
};

export default en;
