const hi = {
  translation: {
    common: {
      next: 'आगे',
      back: 'वापस',
      continue: 'जारी रखें',
      getStarted: 'शुरू करें',
    },

    auth: {
      welcomeBack: 'वापसी पर स्वागत है',
      login: 'लॉग इन',
      createAccount: 'खाता बनाएं',
      forgotPassword: 'पासवर्ड भूल गए?',
    },
    dashboard: {
      overview: 'ओवरव्यू',
      guard: 'गार्ड',
      sites: 'साइट्स',
      incidents: 'घटनाएं',
      plan: 'प्लान',
      profile: 'प्रोफ़ाइल',
      quickSummary: 'त्वरित सारांश',
      today: 'आज',
      guardsOnDuty: 'ड्यूटी पर गार्ड',
      activeSites: 'सक्रिय साइट्स',
      openIncidents: 'खुली घटनाएं',
      unassignedGuards: 'असाइन न किए गए गार्ड',
      viewDetails: 'विवरण देखें',
      payrollSummary: 'पेरोल सारांश',
      invoices: 'इनवॉइस',
      clientReviews: 'क्लाइंट समीक्षाएं',
      quickActions: 'त्वरित कार्य',
      liveStatus: 'लाइव स्थिति',
      viewAll: 'सभी देखें',
      onDuty: 'ड्यूटी पर',
      addGuard: '+ गार्ड',
      addSite: '+ साइट जोड़ें',
      incident: 'घटना',
      fileIncident: 'घटना दर्ज करें',
      searchSites: 'साइट खोजें...',
      filter: 'फ़िल्टर',
      loadingSites: 'साइट्स लोड हो रही हैं...',
      noSites: 'कोई साइट नहीं मिली।',
      loadingIncidents: 'घटनाएं लोड हो रही हैं...',
      noIncidents: 'कोई घटना नहीं मिली।',
      unableToLoadSites: 'साइट्स लोड नहीं हो सकीं।',
      unableToLoadIncidents: 'घटनाएं लोड नहीं हो सकीं।',
      site: 'साइट',
      selectSite: 'साइट चुनें',
      all: 'सभी',
      severity: 'गंभीरता',
      low: 'कम',
      medium: 'मध्यम',
      high: 'उच्च',
      notes: 'नोट्स',
      describeIncident: 'बताएं क्या हुआ...',
      uploadPhotos: 'फ़ोटो अपलोड करें',
      optional: '(वैकल्पिक)',
      addPhotos: 'फ़ोटो जोड़ें',
      maxPhotos: 'अधिकतम 5 फ़ोटो, प्रत्येक 10MB तक',
      filing: 'दर्ज हो रहा है...',
      incidentFiled: 'घटना सफलतापूर्वक दर्ज हुई',
      incidentRecorded: 'आपकी घटना दर्ज कर ली गई है और इसकी समीक्षा की जाएगी।',
      siteName: 'साइट का नाम',
      address: 'पता',
      enterSiteName: 'साइट का नाम दर्ज करें',
      enterCompleteAddress: 'पूरा पता दर्ज करें',
      startTyping: 'सुझाव के लिए टाइप करना शुरू करें',
      locationGps: 'स्थान (GPS)',
      noGps: 'कोई GPS स्थान नहीं मिला',
      useCurrentLocation: 'वर्तमान स्थान का उपयोग करें',
      coveragePlan: 'कवरेज प्लान',
      dayShift: 'डे शिफ्ट',
      nightWatch: 'नाइट वॉच',
      coverage24x7: '24×7 कवरेज',
      startTime: 'शुरू होने का समय',
      endTime: 'समाप्ति का समय',
      saveSite: 'साइट सहेजें',
      saving: 'सहेजा जा रहा है...',
      addressNotProvided: 'पता उपलब्ध नहीं है',
      guardDataUnavailable: 'गार्ड डेटा उपलब्ध नहीं है',
      notSet: 'सेट नहीं है',
      notScheduled: 'निर्धारित नहीं है',
      myProfile: 'मेरी प्रोफ़ाइल',
      settings: 'सेटिंग्स',
      language: 'भाषा',
      appearance: 'दिखावट',
      light: 'लाइट',
      dark: 'डार्क',
      system: 'सिस्टम',
      logOut: 'लॉग आउट',
      english: 'अंग्रेज़ी',
      hindi: 'हिंदी',
      punjabi: 'पंजाबी',
      missingDetails: 'जानकारी अधूरी है',
      selectSiteAndDescribe: 'साइट चुनें और घटना का विवरण लिखें।',
      siteAndAddressRequired: 'साइट का नाम और पता आवश्यक हैं।',
      couldNotFile: 'घटना दर्ज नहीं हो सकी',
      couldNotLoadSites: 'साइट्स लोड नहीं हो सकीं',
      tryAgain: 'कृपया पुनः प्रयास करें।',
      photoUploadSoon: 'फोटो अपलोड जल्द जोड़ा जाएगा।',
      gpsSoon: 'GPS स्थान सुविधा जल्द जोड़ी जाएगी।',
      close: 'बंद करें',
      tapGuardDetails: 'गार्ड की जानकारी देखने या बदलने के लिए उस पर टैप करें',
      loadingGuards: 'गार्ड लोड हो रहे हैं...',
      noGuardsOnDuty: 'अभी कोई गार्ड ड्यूटी पर नहीं है।',
      unableToLoadGuards: 'गार्ड लोड नहीं हो सके।',
      unassignedSite: 'असाइन नहीं की गई साइट',
      live: 'लाइव',
      noLocationYet: 'अभी कोई स्थान नहीं',
      tapSiteManage: 'साइट्स टैब में प्रबंधित करने के लिए साइट पर टैप करें',
      active: 'सक्रिय',
      guardCount: '{{count}} गार्ड',
      agencyAdmin: 'एजेंसी एडमिन',
      accountDetails: 'खाता विवरण',
      yourAccount: 'आपका खाता',
      fullName: 'पूरा नाम',
      mobileNumber: 'मोबाइल नंबर',
      emailAddress: 'ईमेल पता',
      state: 'राज्य',
      district: 'जिला',
      city: 'शहर',
      pincode: 'पिनकोड',
      saveChanges: 'बदलाव सहेजें',
      signOut: 'साइन आउट',
      profilePhoto: 'प्रोफ़ाइल फोटो',
      loadingProfile: 'प्रोफ़ाइल लोड हो रही है...',
      profileRequired: 'सभी आवश्यक खाते के फ़ील्ड भरें।',
      changesSaved: 'आपके बदलाव सहेज लिए गए हैं।',
      offlineAddressHint: 'ऑफ़लाइन होने पर पते के सुझाव उपलब्ध नहीं हैं।',
      rotateCoverage: '24 घंटे की कवरेज के लिए गार्ड शिफ्ट में बदलते रहते हैं।',
      selectedPlan: 'चुना गया कवरेज प्लान इस साइट के लिए इस्तेमाल होगा।',
      getDirections: 'दिशा प्राप्त करें',
      directionsUnavailable: 'मैप इंटीग्रेशन जुड़ने पर दिशा उपलब्ध होगी।',
      removeSite: 'साइट हटाएं',
      siteUpdateUnavailable:
        'साइट बदलाव और हटाने के लिए बैकएंड अपडेट/डिलीट एंडपॉइंट की आवश्यकता है।',
      searchGuards: 'नाम, आईडी या साइट से गार्ड खोजें',
      offDuty: 'ऑफ ड्यूटी',
      noGuardsFound: 'कोई गार्ड नहीं मिला।',
      callGuard: 'गार्ड को कॉल करें',
      guardAddUnavailable: 'गार्ड जोड़ने का फॉर्म जल्द जोड़ा जाएगा।',
    },
  },
};

export default hi;
