const hi = {
  translation: {
    addGuardForm: {
      title: 'गार्ड जोड़ें',
      fullName: 'पूरा नाम',
      mobileNumber: 'मोबाइल नंबर',
      email: 'ईमेल',
      password: 'पासवर्ड',
      joiningDate: 'नियुक्ति की तारीख',
      address: 'पता (वैकल्पिक)',
      age: 'आयु (वैकल्पिक)',
      gender: 'लिंग (वैकल्पिक)',
      male: 'पुरुष',
      female: 'महिला',
      other: 'अन्य',
      site: 'प्रारंभिक साइट आवंटन',
      unassigned: 'आवंटित नहीं',
      loadingSites: 'साइट लोड हो रही हैं…',
      siteError:
        'साइट लोड नहीं हुईं। बिना साइट के गार्ड जोड़ें या फ़ॉर्म दोबारा खोलें।',
      coveragePlan: 'कवरेज योजना',
      day_shift: 'दिन की शिफ्ट',
      night_watch: 'रात की शिफ्ट',
      '24x7': '24×7 कवरेज',
      shiftHours: 'शिफ्ट अवधि',
      hours: 'घंटे',
      startTime: 'आरंभ समय',
      endTime: 'समाप्ति समय',
      endHint: 'समाप्ति समय चुनी गई अवधि के अनुसार तय होगा, रात की शिफ्ट सहित।',
      coverageHint:
        '24×7 कवरेज में बारी-बारी से शिफ्ट होती हैं; यहाँ अलग शिफ्ट अवधि नहीं दी जाती।',
      basicSalary: 'मूल वेतन (वैकल्पिक)',
      allowances: 'भत्ते (वैकल्पिक)',
      requiredHint: '* वाले फ़ील्ड आवश्यक हैं।',
      requiredError: 'सभी आवश्यक फ़ील्ड भरें।',
      contactError:
        'मान्य 10 अंकों का भारतीय मोबाइल, ईमेल और कम से कम 6 अक्षरों का पासवर्ड दर्ज करें।',
      dateError: 'मान्य तारीख YYYY-MM-DD में दर्ज करें।',
      ageError: 'आयु 18 से 65 के बीच पूर्णांक होनी चाहिए।',
      salaryError:
        'वेतन और भत्ते शून्य या अधिक, अधिकतम दो दशमलव अंकों में दर्ज करें।',
      success: 'गार्ड सफलतापूर्वक जोड़ा गया।',
      failure: 'गार्ड नहीं जुड़ा। फिर कोशिश करें।',
      saving: 'सहेजा जा रहा है…',
      search: 'विकल्प खोजें',
      noResults: 'कोई विकल्प नहीं मिला।',
      close: 'बंद करें',
    },
    common: {
      next: 'आगे',
      back: 'वापस',
      continue: 'जारी रखें',
      getStarted: 'शुरू करें',
    },

    auth: {
      welcomeBack: 'वापसी पर स्वागत है',
      login: 'लॉग इन',
      createAccount: 'खाता बनाएं',
      forgotPassword: 'पासवर्ड भूल गए?',
      enterValidIdentifier: 'मान्य ईमेल पता या मोबाइल नंबर दर्ज करें।',
      couldNotSendOtp: 'OTP नहीं भेजा जा सका',
      identifierPlaceholder: 'ईमेल या +91 मोबाइल नंबर',
      passwordChanged: 'आपका पासवर्ड सफलतापूर्वक बदल दिया गया है।',
      invalidOtp: 'अमान्य OTP',
      completeOtp: 'पूरा 6 अंकों का सत्यापन कोड दर्ज करें।',
      verificationFailed: 'सत्यापन विफल',
      identifierFallback: 'आपका ईमेल या मोबाइल नंबर',
      otpDigit: 'OTP अंक {{number}}',
      mobileOtpDigit: 'मोबाइल सत्यापन अंक {{number}}',
      loginSubtitle: 'जारी रखने के लिए लॉग इन करें',
      emailAddress: 'ईमेल पता',
      password: 'पासवर्ड',
      enterPassword: 'अपना पासवर्ड दर्ज करें',
      showPassword: 'पासवर्ड दिखाएं',
      hidePassword: 'पासवर्ड छिपाएं',
      loggingIn: 'लॉग इन हो रहा है...',
      orContinueWith: 'या इसके साथ जारी रखें',
      noAccount: 'खाता नहीं है?',
      signUp: 'साइन अप करें',
      invalidDetails: 'अमान्य जानकारी',
      enterLinkedEmail: 'अपने खाते से जुड़ा ईमेल पता दर्ज करें।',
      invalidPassword: 'अमान्य पासवर्ड',
      loginFailed: 'लॉग इन विफल',
      tryAgain: 'कृपया फिर कोशिश करें।',
      createSubtitle: 'शुरू करने के लिए अपनी जानकारी भरें',
      fullName: 'पूरा नाम',
      mobileNumber: 'मोबाइल नंबर',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      exampleName: 'जैसे आकाश सिंह',
      alreadyAccount: 'पहले से खाता है?',
      invalidName: 'अमान्य नाम',
      enterFullName: 'अपना पूरा नाम दर्ज करें।',
      invalidEmail: 'अमान्य ईमेल पता',
      enterValidEmail: 'मान्य ईमेल पता दर्ज करें।',
      passwordsMismatch: 'पासवर्ड मेल नहीं खाते',
      passwordsMismatchMessage: 'पासवर्ड और पुष्टि समान होनी चाहिए।',
      accountFailed: 'खाता नहीं बनाया जा सका',
      backToSuperAdmin: 'सुपर एडमिन पर वापस जाएं',
      goBack: 'वापस जाएं',
      forgotTitle: 'पासवर्ड भूल गए',
      emailOrMobile: 'ईमेल या मोबाइल नंबर',
      rememberPassword: 'पासवर्ड याद है?',
      sendOtp: 'OTP भेजें',
      sending: 'भेजा जा रहा है...',
      forgotSubtitle: 'अपना पंजीकृत ईमेल या मोबाइल नंबर दर्ज करें',
      verifyMobile: 'मोबाइल नंबर सत्यापित करें',
      verifyOtp: 'OTP सत्यापित करें',
      enterCodeSent: 'भेजा गया 6 अंकों का कोड दर्ज करें',
      didNotReceive: 'OTP नहीं मिला?',
      resendOtp: 'OTP फिर भेजें',
      resendIn: '00:30 में',
      verifyContinue: 'सत्यापित करें और जारी रखें',
      verifying: 'सत्यापन हो रहा है...',
      couldNotResend: 'OTP फिर नहीं भेजा जा सका',
      newPassword: 'नया पासवर्ड',
      enterNewPassword: 'नया पासवर्ड दर्ज करें',
      confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
      newPasswordSubtitle: 'अपना नया पासवर्ड दर्ज करें',
      resetPassword: 'पासवर्ड रीसेट करें',
      resetting: 'रीसेट हो रहा है...',
      passwordUpdated: 'पासवर्ड सफलतापूर्वक अपडेट हुआ!',
      passwordUpdatedMessage:
        'आपका पासवर्ड अपडेट हो गया है। अब आप नए पासवर्ड से लॉग इन कर सकते हैं।',
      goToLogin: 'लॉग इन पर जाएं',
      invalidMobile: 'अमान्य मोबाइल नंबर',
      enterValidMobile: 'मान्य 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।',
      confirmMustMatch: 'पुष्टि पासवर्ड से मेल खानी चाहिए।',
      accountType: 'खाता प्रकार',
      chooseAccountType: 'अपना खाता प्रकार चुनें...',
      agency: 'एजेंसी',
      client: 'क्लाइंट',
      agencyDescription: 'गार्ड और सुरक्षा सेवाएं\nप्रबंधित करें',
      clientDescription: 'सुरक्षा सेवाएं नियुक्त और\nप्रबंधित करें',
      creatingAccount: 'खाता बनाया जा रहा है...',
    },
    onboarding: {
      step1: {
        title: 'लोग सुरक्षित,\nस्थान सुरक्षित।',
        subtitle: 'पेशेवर सुरक्षा प्रबंधन अब सरल, भरोसेमंद और कुशल।',
      },
      step2: {
        title: 'कभी भी, कहीं भी प्रबंधन करें',
        subtitle: 'आप जहां भी हों, अपने सुरक्षा संचालन से जुड़े रहें।',
      },
      step3: {
        title: 'सतर्क रहें, तेजी से प्रतिक्रिया दें।',
        subtitle: 'अपडेट पाएं और घटनाओं पर बिना देरी प्रतिक्रिया दें।',
      },
    },
    superAdmin: {
      agencies: 'एजेंसियां',
      approvals: 'अनुमोदन',
      liveStatus: 'लाइव स्थिति',
      profile: 'प्रोफ़ाइल',
      addAgency: 'नई एजेंसी जोड़ें',
      searchAgencies: 'नाम से एजेंसी खोजें',
      active: 'सक्रिय',
      inactive: 'गैर-सक्रिय',
      guards: 'गार्ड',
      clients: 'क्लाइंट',
      loadingAgencies: 'एजेंसियां लोड हो रही हैं',
      unableAgencies: 'एजेंसियां लोड नहीं हो सकीं।',
      noMatching: 'कोई मेल खाती एजेंसी नहीं',
      noInactive: 'कोई गैर-सक्रिय एजेंसी नहीं',
      noActive: 'अभी कोई सक्रिय एजेंसी नहीं',
      searchHint: 'दूसरा एजेंसी नाम खोजें या स्थिति फ़िल्टर बदलें।',
      approvalHint:
        'अनुमोदित एजेंसियां सुपर एडमिन समीक्षा के बाद यहां दिखेंगी।',
      networkTitle: 'आपका नेटवर्क एक नज़र में',
      liveUnavailable: 'लाइव रिपोर्टिंग अभी उपलब्ध नहीं है।',
      agencyApprovals: 'एजेंसी अनुमोदन',
      refreshRequests: 'अनुरोध रीफ्रेश करें',
      noPending: 'कोई एजेंसी अनुमोदन की प्रतीक्षा में नहीं है।',
      approve: 'अनुमोदित करें',
      reject: 'अस्वीकार करें',
      notifications: 'सूचनाएं',
      markAllRead: 'सभी पढ़ा हुआ करें',
      reviewApprovals: 'एजेंसी अनुमोदन देखें',
      loadingNotifications: 'सूचनाएं लोड हो रही हैं…',
      tryAgain: 'फिर कोशिश करें',
      noNotifications: 'अभी कोई सूचना नहीं',
      deleteNotification: 'सूचना हटाएं?',
      deleteNotificationMessage: 'यह सूचना हटा दी जाएगी।',
      delete: 'हटाएं',
      cancel: 'रद्द करें',
      loadingProfile: 'प्रोफ़ाइल लोड हो रही है…',
      profilePhoto: 'प्रोफ़ाइल फोटो',
      photoSoon: 'प्रोफ़ाइल फोटो अपलोड जल्द उपलब्ध होगा।',
      yourAccount: 'आपका खाता',
      accountId: 'खाता आईडी: {{id}}',
      fullName: 'पूरा नाम',
      email: 'ईमेल',
      mobileNumber: 'मोबाइल नंबर',
      saving: 'सहेजा जा रहा है…',
      saveChanges: 'बदलाव सहेजें',
      signOut: 'साइन आउट',
      profileUpdated: 'प्रोफ़ाइल अपडेट हुई',
      changesSaved: 'आपके बदलाव सहेज दिए गए हैं।',
      fullNameRequired: 'पूरा नाम आवश्यक है',
      enterFullName: 'सुपर एडमिन का पूरा नाम दर्ज करें।',
      invalidEmail: 'अमान्य ईमेल',
      enterEmail: 'मान्य ईमेल पता दर्ज करें।',
      invalidPhone: 'अमान्य फोन नंबर',
      enterPhone: 'मान्य 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।',
      editAgency: 'एजेंसी संपादित करें',
      manageAgency: 'एजेंसी खाते की जानकारी प्रबंधित करें',
      agencyDetails: 'एजेंसी विवरण',
      accountDetails: 'खाता विवरण',
      businessDetails: 'व्यवसाय विवरण',
      address: 'पता',
      status: 'स्थिति',
      leavePassword: 'मौजूदा रखने के लिए खाली छोड़ें',
      removeAgency: 'एजेंसी हटाएं',
      agencyUpdated: 'एजेंसी अपडेट हुई',
      agencySaved: 'एजेंसी की जानकारी सहेज दी गई है।',
      loadingLocations: 'स्थान लोड हो रहे हैं…',
      closeEditor: 'एजेंसी संपादक बंद करें',
    },
    details: {
      agencyTitle: 'एजेंसी विवरण',
      agencySubtitle: 'अपनी एजेंसी के बारे में बताएं',
      agencyName: 'एजेंसी / कंपनी का नाम',
      enterAgencyName: 'एजेंसी का नाम दर्ज करें',
      businessType: 'व्यवसाय का प्रकार',
      gstNumber: 'GST नंबर (वैकल्पिक)',
      enterGst: 'GST नंबर दर्ज करें',
      officeAddress: 'कार्यालय का पता',
      enterOfficeAddress: 'कार्यालय का पता दर्ज करें',
      clientTitle: 'क्लाइंट विवरण',
      clientSubtitle: 'अपने संगठन के बारे में बताएं',
      companyName: 'कंपनी / संगठन का नाम',
      enterCompanyName: 'कंपनी का नाम दर्ज करें',
      siteName: 'साइट / संपत्ति का नाम',
      enterSiteName: 'साइट/संपत्ति का नाम दर्ज करें',
      siteAddress: 'साइट का पता',
      enterSiteAddress: 'साइट का पता दर्ज करें',
      enterCity: 'शहर दर्ज करें',
      selectState: 'राज्य चुनें',
      enterPincode: 'पिनकोड दर्ज करें',
      loadingLocations: 'स्थान लोड हो रहे हैं…',
      closeLocations: 'स्थान विकल्प बंद करें',
      agencyNameRequired: 'एजेंसी का नाम आवश्यक है',
      enterAgencyCompany: 'अपनी एजेंसी या कंपनी का नाम दर्ज करें।',
      businessRequired: 'व्यवसाय प्रकार आवश्यक है',
      selectBusiness: 'अपना व्यवसाय प्रकार चुनें।',
      officeRequired: 'कार्यालय पता आवश्यक है',
      enterOffice: 'कार्यालय का पता दर्ज करें।',
      cityRequired: 'शहर आवश्यक है',
      enterYourCity: 'अपना शहर दर्ज करें।',
      stateRequired: 'राज्य आवश्यक है',
      selectStateTerritory: 'अपना राज्य या केंद्र शासित प्रदेश चुनें।',
      districtRequired: 'जिला आवश्यक है',
      selectDistrict: 'अपना जिला चुनें।',
      invalidPincode: 'अमान्य पिनकोड',
      enterValidPincode: 'मान्य 6 अंकों का पिनकोड दर्ज करें।',
      siteNameRequired: 'साइट का नाम आवश्यक है',
      enterProperty: 'अपनी साइट या संपत्ति का नाम दर्ज करें।',
      siteAddressRequired: 'साइट का पता आवश्यक है',
      enterAddress: 'साइट का पता दर्ज करें।',
    },
    client: {
      home: 'होम',
      request: 'अनुरोध',
      invoices: 'इनवॉइस',
      alerts: 'अलर्ट',
      profile: 'प्रोफ़ाइल',
      portal: 'क्लाइंट पोर्टल',
      loading: 'क्लाइंट विवरण लोड हो रहा है…',
      loadFailed: 'क्लाइंट विवरण लोड नहीं हो सका।',
      yourAgencies: 'आपकी एजेंसियां',
      noAgency: 'कोई एजेंसी असाइन नहीं है',
      noAgencyHint: 'आपकी असाइन की गई सुरक्षा एजेंसी यहां दिखाई देगी।',
      coveragePlan: 'कवरेज योजना',
      noCoverage: 'कोई कवरेज योजना नहीं',
      noCoverageHint: 'एजेंसी असाइन होने पर कवरेज विवरण यहां दिखाई देगा।',
      requestCoverage: 'सुरक्षा कवरेज का अनुरोध करें',
      requestHint: 'कवरेज अनुरोध सुविधा यहां दिखाई देगी।',
      noInvoices: 'कोई इनवॉइस नहीं',
      noInvoicesHint: 'उपलब्ध होने पर आपके इनवॉइस यहां दिखाई देंगे।',
      noAlerts: 'कोई अलर्ट नहीं',
      noAlertsHint: 'सुरक्षा और खाते के अलर्ट यहां दिखाई देंगे।',
    },
    coverageRequest: {
      location: 'आपका स्थान',
      eventName: 'कार्यक्रम का नाम',
      eventPlaceholder: 'कार्यक्रम का नाम दर्ज करें',
      siteLocation: 'साइट या कार्यक्रम का स्थान',
      sitePlaceholder: 'जैसे ईस्ट विंग प्रवेश',
      guardsNeeded: 'आवश्यक गार्ड',
      notes: 'नोट्स',
      notesPlaceholder: 'तारीखें, शिफ्ट समय, विशेष आवश्यकताएं…',
      send: 'अनुरोध भेजें',
      sending: 'भेजा जा रहा है…',
      myRequests: 'मेरे अनुरोध',
      none: 'अभी कोई कवरेज अनुरोध नहीं है।',
      required: 'सभी आवश्यक फ़ील्ड भरें।',
      sentTitle: 'अनुरोध भेजा गया',
      sentMessage: 'आपका कवरेज अनुरोध जमा हो गया है।',
      sendFailed: 'अनुरोध नहीं भेजा जा सका।',
      loadFailed: 'अनुरोध लोड नहीं हो सके।',
      locationFailed: 'स्थान लोड नहीं हो सके।',
      selectStateFirst: 'पहले राज्य चुनें।',
      selectDistrictFirst: 'पहले जिला चुनें।',
      agenciesInArea: 'आपके क्षेत्र की एजेंसियां',
      noAgenciesInArea:
        'इस जिले में अभी कोई एजेंसी नहीं मिली — पास का जिला आज़माएं।',
      agenciesFailed: 'इस जिले की एजेंसियां लोड नहीं हो सकीं।',
      available: 'उपलब्ध',
      selectAgency: 'चुनें',
      changeAgency: 'बदलें',
      status: {
        pending: 'लंबित',
        approved: 'अनुमोदित',
        rejected: 'अस्वीकृत',
        assigned: 'असाइन किया गया',
        completed: 'पूर्ण',
        cancelled: 'रद्द',
      },
    },
    dashboard: {
      dashboard: 'डैशबोर्ड',
      overview: 'ओवरव्यू',
      guard: 'गार्ड',
      sites: 'साइट्स',
      incidents: 'घटनाएं',
      plan: 'प्लान',
      profile: 'प्रोफ़ाइल',
      quickSummary: 'त्वरित सारांश',
      today: 'आज',
      guardsOnDuty: 'ड्यूटी पर गार्ड',
      activeSites: 'सक्रिय साइट्स',
      openIncidents: 'खुली घटनाएं',
      unassignedGuards: 'असाइन न किए गए गार्ड',
      viewDetails: 'विवरण देखें',
      payrollSummary: 'पेरोल सारांश',
      invoices: 'इनवॉइस',
      clientReviews: 'क्लाइंट समीक्षाएं',
      quickActions: 'त्वरित कार्य',
      liveStatus: 'लाइव स्थिति',
      viewAll: 'सभी देखें',
      onDuty: 'ड्यूटी पर',
      addGuard: '+ गार्ड',
      addSite: '+ साइट जोड़ें',
      incident: 'घटना',
      fileIncident: 'घटना दर्ज करें',
      searchSites: 'साइट खोजें...',
      filter: 'फ़िल्टर',
      loadingSites: 'साइट्स लोड हो रही हैं...',
      noSites: 'कोई साइट नहीं मिली।',
      loadingIncidents: 'घटनाएं लोड हो रही हैं...',
      noIncidents: 'कोई घटना नहीं मिली।',
      unableToLoadSites: 'साइट्स लोड नहीं हो सकीं।',
      unableToLoadIncidents: 'घटनाएं लोड नहीं हो सकीं।',
      site: 'साइट',
      selectSite: 'साइट चुनें',
      selectInitialSite: 'प्रारंभिक साइट चुनें',
      selectJoiningDate: 'नियुक्ति की तारीख चुनें',
      year: 'वर्ष',
      month: 'महीना',
      date: 'तारीख',
      done: 'हो गया',
      showPassword: 'पासवर्ड दिखाएं',
      hidePassword: 'पासवर्ड छिपाएं',
      previousMonth: 'पिछला महीना',
      nextMonth: 'अगला महीना',
      editGuard: 'गार्ड संपादित करें',
      guardUpdated: 'गार्ड की जानकारी सफलतापूर्वक अपडेट हुई।',
      newGuardPassword: 'नया पासवर्ड (वैकल्पिक)',
      leavePasswordBlank: 'वर्तमान पासवर्ड रखने के लिए खाली छोड़ें',
      removeGuard: 'गार्ड हटाएं',
      removeGuardConfirmation:
        'इस गार्ड को हटाएं? उनका लॉगिन बंद हो जाएगा। इसे वापस नहीं किया जा सकता।',
      cancel: 'रद्द करें',
      all: 'सभी',
      severity: 'गंभीरता',
      low: 'कम',
      medium: 'मध्यम',
      high: 'उच्च',
      notes: 'नोट्स',
      describeIncident: 'बताएं क्या हुआ...',
      uploadPhotos: 'फ़ोटो अपलोड करें',
      optional: '(वैकल्पिक)',
      addPhotos: 'फ़ोटो जोड़ें',
      maxPhotos: 'अधिकतम 5 फ़ोटो, प्रत्येक 10MB तक',
      filing: 'दर्ज हो रहा है...',
      incidentFiled: 'घटना सफलतापूर्वक दर्ज हुई',
      incidentRecorded: 'आपकी घटना दर्ज कर ली गई है और इसकी समीक्षा की जाएगी।',
      siteName: 'साइट का नाम',
      address: 'पता',
      enterSiteName: 'साइट का नाम दर्ज करें',
      enterCompleteAddress: 'पूरा पता दर्ज करें',
      startTyping: 'सुझाव के लिए टाइप करना शुरू करें',
      locationGps: 'स्थान (GPS)',
      noGps: 'कोई GPS स्थान नहीं मिला',
      useCurrentLocation: 'वर्तमान स्थान का उपयोग करें',
      coveragePlan: 'कवरेज प्लान',
      dayShift: 'डे शिफ्ट',
      nightWatch: 'नाइट वॉच',
      coverage24x7: '24×7 कवरेज',
      startTime: 'शुरू होने का समय',
      endTime: 'समाप्ति का समय',
      saveSite: 'साइट सहेजें',
      saving: 'सहेजा जा रहा है...',
      addressNotProvided: 'पता उपलब्ध नहीं है',
      guardDataUnavailable: 'गार्ड डेटा उपलब्ध नहीं है',
      notSet: 'सेट नहीं है',
      notScheduled: 'निर्धारित नहीं है',
      myProfile: 'मेरी प्रोफ़ाइल',
      settings: 'सेटिंग्स',
      language: 'भाषा',
      appearance: 'दिखावट',
      light: 'लाइट',
      dark: 'डार्क',
      system: 'सिस्टम',
      logOut: 'लॉग आउट',
      english: 'अंग्रेज़ी',
      hindi: 'हिंदी',
      punjabi: 'पंजाबी',
      missingDetails: 'जानकारी अधूरी है',
      selectSiteAndDescribe: 'साइट चुनें और घटना का विवरण लिखें।',
      siteAndAddressRequired: 'साइट का नाम और पता आवश्यक हैं।',
      couldNotFile: 'घटना दर्ज नहीं हो सकी',
      couldNotLoadSites: 'साइट्स लोड नहीं हो सकीं',
      tryAgain: 'कृपया पुनः प्रयास करें।',
      photoUploadSoon: 'फोटो अपलोड जल्द जोड़ा जाएगा।',
      gpsSoon: 'GPS स्थान सुविधा जल्द जोड़ी जाएगी।',
      close: 'बंद करें',
      tapGuardDetails: 'गार्ड की जानकारी देखने या बदलने के लिए उस पर टैप करें',
      loadingGuards: 'गार्ड लोड हो रहे हैं...',
      noGuardsOnDuty: 'अभी कोई गार्ड ड्यूटी पर नहीं है।',
      unableToLoadGuards: 'गार्ड लोड नहीं हो सके।',
      unassignedSite: 'असाइन नहीं की गई साइट',
      live: 'लाइव',
      noLocationYet: 'अभी कोई स्थान नहीं',
      tapSiteManage: 'साइट्स टैब में प्रबंधित करने के लिए साइट पर टैप करें',
      active: 'सक्रिय',
      guardCount: '{{count}} गार्ड',
      agencyAdmin: 'एजेंसी एडमिन',
      accountDetails: 'खाता विवरण',
      yourAccount: 'आपका खाता',
      fullName: 'पूरा नाम',
      mobileNumber: 'मोबाइल नंबर',
      emailAddress: 'ईमेल पता',
      state: 'राज्य',
      district: 'जिला',
      city: 'शहर',
      pincode: 'पिनकोड',
      saveChanges: 'बदलाव सहेजें',
      signOut: 'साइन आउट',
      profilePhoto: 'प्रोफ़ाइल फोटो',
      loadingProfile: 'प्रोफ़ाइल लोड हो रही है...',
      profileRequired: 'सभी आवश्यक खाते के फ़ील्ड भरें।',
      changesSaved: 'आपके बदलाव सहेज लिए गए हैं।',
      offlineAddressHint: 'ऑफ़लाइन होने पर पते के सुझाव उपलब्ध नहीं हैं।',
      rotateCoverage: '24 घंटे की कवरेज के लिए गार्ड शिफ्ट में बदलते रहते हैं।',
      selectedPlan: 'चुना गया कवरेज प्लान इस साइट के लिए इस्तेमाल होगा।',
      getDirections: 'दिशा प्राप्त करें',
      directionsUnavailable: 'मैप इंटीग्रेशन जुड़ने पर दिशा उपलब्ध होगी।',
      removeSite: 'साइट हटाएं',
      siteUpdateUnavailable:
        'साइट बदलाव और हटाने के लिए बैकएंड अपडेट/डिलीट एंडपॉइंट की आवश्यकता है।',
      searchGuards: 'नाम, आईडी या साइट से गार्ड खोजें',
      offDuty: 'ऑफ ड्यूटी',
      noGuardsFound: 'कोई गार्ड नहीं मिला।',
      callGuard: 'गार्ड को कॉल करें',
      guardAddUnavailable: 'गार्ड जोड़ने का फॉर्म जल्द जोड़ा जाएगा।',
      noMatchingLocations: 'कोई मेल खाता स्थान नहीं मिला।',
    },
  },
};

export default hi;
