const pa = {
  translation: {
    common: {
      next: 'ਅੱਗੇ',
      back: 'ਵਾਪਸ',
      continue: 'ਜਾਰੀ ਰੱਖੋ',
      getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    },

    auth: {
      welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
      login: 'ਲਾਗ ਇਨ',
      createAccount: 'ਖਾਤਾ ਬਣਾਓ',
      forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?',
    },
    dashboard: {
      overview: 'ਓਵਰਵਿਊ',
      guard: 'ਗਾਰਡ',
      sites: 'ਸਾਈਟਾਂ',
      incidents: 'ਘਟਨਾਵਾਂ',
      plan: 'ਪਲਾਨ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      quickSummary: 'ਤੁਰੰਤ ਸੰਖੇਪ',
      today: 'ਅੱਜ',
      guardsOnDuty: 'ਡਿਊਟੀ ਉੱਤੇ ਗਾਰਡ',
      activeSites: 'ਸਰਗਰਮ ਸਾਈਟਾਂ',
      openIncidents: 'ਖੁੱਲ੍ਹੀਆਂ ਘਟਨਾਵਾਂ',
      unassignedGuards: 'ਨਾ ਲਗਾਏ ਗਾਰਡ',
      viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
      payrollSummary: 'ਪੇਰੋਲ ਸੰਖੇਪ',
      invoices: 'ਇਨਵੌਇਸ',
      clientReviews: 'ਕਲਾਇੰਟ ਸਮੀਖਿਆਵਾਂ',
      quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      liveStatus: 'ਲਾਈਵ ਸਥਿਤੀ',
      viewAll: 'ਸਾਰੇ ਵੇਖੋ',
      onDuty: 'ਡਿਊਟੀ ਉੱਤੇ',
      addGuard: '+ ਗਾਰਡ',
      addSite: '+ ਸਾਈਟ ਜੋੜੋ',
      incident: 'ਘਟਨਾ',
      fileIncident: 'ਘਟਨਾ ਦਰਜ ਕਰੋ',
      searchSites: 'ਸਾਈਟਾਂ ਖੋਜੋ...',
      filter: 'ਫਿਲਟਰ',
      loadingSites: 'ਸਾਈਟਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noSites: 'ਕੋਈ ਸਾਈਟ ਨਹੀਂ ਮਿਲੀ।',
      loadingIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noIncidents: 'ਕੋਈ ਘਟਨਾ ਨਹੀਂ ਮਿਲੀ।',
      unableToLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      unableToLoadIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      site: 'ਸਾਈਟ',
      selectSite: 'ਸਾਈਟ ਚੁਣੋ',
      all: 'ਸਾਰੇ',
      severity: 'ਗੰਭੀਰਤਾ',
      low: 'ਘੱਟ',
      medium: 'ਦਰਮਿਆਨਾ',
      high: 'ਉੱਚ',
      notes: 'ਨੋਟਸ',
      describeIncident: 'ਕੀ ਹੋਇਆ, ਵੇਰਵਾ ਦਿਓ...',
      uploadPhotos: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
      optional: '(ਵਿਕਲਪਿਕ)',
      addPhotos: 'ਫੋਟੋ ਜੋੜੋ',
      maxPhotos: 'ਵੱਧ ਤੋਂ ਵੱਧ 5 ਫੋਟੋਆਂ, ਹਰ ਇੱਕ 10MB ਤੱਕ',
      filing: 'ਦਰਜ ਹੋ ਰਿਹਾ ਹੈ...',
      incidentFiled: 'ਘਟਨਾ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋਈ',
      incidentRecorded: 'ਤੁਹਾਡੀ ਘਟਨਾ ਦਰਜ ਕਰ ਲਈ ਗਈ ਹੈ ਅਤੇ ਸਮੀਖਿਆ ਕੀਤੀ ਜਾਵੇਗੀ।',
      siteName: 'ਸਾਈਟ ਦਾ ਨਾਮ',
      address: 'ਪਤਾ',
      enterSiteName: 'ਸਾਈਟ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      enterCompleteAddress: 'ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      startTyping: 'ਸੁਝਾਵਾਂ ਲਈ ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
      locationGps: 'ਟਿਕਾਣਾ (GPS)',
      noGps: 'ਕੋਈ GPS ਟਿਕਾਣਾ ਨਹੀਂ ਮਿਲਿਆ',
      useCurrentLocation: 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ ਵਰਤੋ',
      coveragePlan: 'ਕਵਰੇਜ ਪਲਾਨ',
      dayShift: 'ਦਿਨ ਦੀ ਸ਼ਿਫਟ',
      nightWatch: 'ਰਾਤ ਦੀ ਨਿਗਰਾਨੀ',
      coverage24x7: '24×7 ਕਵਰੇਜ',
      startTime: 'ਸ਼ੁਰੂਆਤੀ ਸਮਾਂ',
      endTime: 'ਅੰਤ ਸਮਾਂ',
      saveSite: 'ਸਾਈਟ ਸੇਵ ਕਰੋ',
      saving: 'ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ...',
      addressNotProvided: 'ਪਤਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      guardDataUnavailable: 'ਗਾਰਡ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      notSet: 'ਸੈੱਟ ਨਹੀਂ ਹੈ',
      notScheduled: 'ਨਿਰਧਾਰਤ ਨਹੀਂ ਹੈ',
      myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      settings: 'ਸੈਟਿੰਗਾਂ',
      language: 'ਭਾਸ਼ਾ',
      appearance: 'ਦਿੱਖ',
      light: 'ਲਾਈਟ',
      dark: 'ਡਾਰਕ',
      system: 'ਸਿਸਟਮ',
      logOut: 'ਲੌਗ ਆਉਟ',
      english: 'ਅੰਗਰੇਜ਼ੀ',
      hindi: 'ਹਿੰਦੀ',
      punjabi: 'ਪੰਜਾਬੀ',
      missingDetails: 'ਵੇਰਵੇ ਅਧੂਰੇ ਹਨ',
      selectSiteAndDescribe: 'ਸਾਈਟ ਚੁਣੋ ਅਤੇ ਘਟਨਾ ਦਾ ਵੇਰਵਾ ਦਿਓ।',
      siteAndAddressRequired: 'ਸਾਈਟ ਦਾ ਨਾਮ ਅਤੇ ਪਤਾ ਲਾਜ਼ਮੀ ਹਨ।',
      couldNotFile: 'ਘਟਨਾ ਦਰਜ ਨਹੀਂ ਹੋ ਸਕੀ',
      couldNotLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ',
      tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      photoUploadSoon: 'ਫੋਟੋ ਅੱਪਲੋਡ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
      gpsSoon: 'GPS ਟਿਕਾਣਾ ਸਹੂਲਤ ਜਲਦੀ ਜੋੜੀ ਜਾਵੇਗੀ।',
      close: 'ਬੰਦ ਕਰੋ',
      tapGuardDetails: 'ਗਾਰਡ ਦੇ ਵੇਰਵੇ ਦੇਖਣ ਜਾਂ ਸੋਧਣ ਲਈ ਟੈਪ ਕਰੋ',
      loadingGuards: 'ਗਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
      noGuardsOnDuty: 'ਇਸ ਵੇਲੇ ਕੋਈ ਗਾਰਡ ਡਿਊਟੀ ਉੱਤੇ ਨਹੀਂ ਹੈ।',
      unableToLoadGuards: 'ਗਾਰਡ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      unassignedSite: 'ਨਾ ਲਗਾਈ ਸਾਈਟ',
      live: 'ਲਾਈਵ',
      noLocationYet: 'ਹਾਲੇ ਕੋਈ ਟਿਕਾਣਾ ਨਹੀਂ',
      tapSiteManage: 'ਸਾਈਟਾਂ ਟੈਬ ਵਿੱਚ ਪ੍ਰਬੰਧਨ ਲਈ ਸਾਈਟ ਉੱਤੇ ਟੈਪ ਕਰੋ',
      active: 'ਸਰਗਰਮ',
      guardCount: '{{count}} ਗਾਰਡ',
      agencyAdmin: 'ਏਜੰਸੀ ਐਡਮਿਨ',
      accountDetails: 'ਖਾਤੇ ਦੇ ਵੇਰਵੇ',
      yourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      emailAddress: 'ਈਮੇਲ ਪਤਾ',
      state: 'ਰਾਜ',
      district: 'ਜ਼ਿਲ੍ਹਾ',
      city: 'ਸ਼ਹਿਰ',
      pincode: 'ਪਿੰਨਕੋਡ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
      loadingProfile: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
      profileRequired: 'ਖਾਤੇ ਦੇ ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      changesSaved: 'ਤੁਹਾਡੀਆਂ ਤਬਦੀਲੀਆਂ ਸੇਵ ਹੋ ਗਈਆਂ ਹਨ।',
      offlineAddressHint: 'ਆਫਲਾਈਨ ਹੋਣ ਤੇ ਪਤੇ ਦੇ ਸੁਝਾਅ ਉਪਲਬਧ ਨਹੀਂ ਹਨ।',
      rotateCoverage: '24 ਘੰਟਿਆਂ ਦੀ ਕਵਰੇਜ ਲਈ ਗਾਰਡ ਸ਼ਿਫਟਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।',
      selectedPlan: 'ਚੁਣਿਆ ਕਵਰੇਜ ਪਲਾਨ ਇਸ ਸਾਈਟ ਲਈ ਵਰਤਿਆ ਜਾਵੇਗਾ।',
      getDirections: 'ਦਿਸ਼ਾਵਾਂ ਲਵੋ',
      directionsUnavailable:
        'ਮੈਪ ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਜੁੜਨ ਤੋਂ ਬਾਅਦ ਦਿਸ਼ਾਵਾਂ ਉਪਲਬਧ ਹੋਣਗੀਆਂ।',
      removeSite: 'ਸਾਈਟ ਹਟਾਓ',
      siteUpdateUnavailable:
        'ਸਾਈਟ ਨੂੰ ਸੋਧਣ ਜਾਂ ਹਟਾਉਣ ਲਈ ਬੈਕਐਂਡ ਅਪਡੇਟ/ਡਿਲੀਟ ਐਂਡਪੌਇੰਟ ਦੀ ਲੋੜ ਹੈ।',
      searchGuards: 'ਨਾਮ, ਆਈਡੀ ਜਾਂ ਸਾਈਟ ਨਾਲ ਗਾਰਡ ਖੋਜੋ',
      offDuty: 'ਆਫ ਡਿਊਟੀ',
      noGuardsFound: 'ਕੋਈ ਗਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
      callGuard: 'ਗਾਰਡ ਨੂੰ ਕਾਲ ਕਰੋ',
      guardAddUnavailable: 'ਗਾਰਡ ਜੋੜਨ ਵਾਲਾ ਫਾਰਮ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
    },
  },
};

export default pa;
