const pa = {
  translation: {
    guardProfile: {
      role: 'ਸੁਰੱਖਿਆ ਗਾਰਡ',
      empId: 'EMP ID: {{id}}',
      personalInformation: 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ',
      documents: 'ਦਸਤਾਵੇਜ਼',
      bankDetails: 'ਬੈਂਕ ਵੇਰਵੇ',
      emergencyContact: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
      settings: 'ਸੈਟਿੰਗਾਂ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profilePhoto: 'ਪ੍ਰੋਫ਼ਾਈਲ ਫੋਟੋ',
      loadingProfile: 'ਪ੍ਰੋਫ਼ਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…',
      loadFailed: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫ਼ਾਈਲ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀ।',
      tryAgain: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      comingSoon: 'ਇਹ ਭਾਗ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗਾ।',
      guardId: 'ਗਾਰਡ ID',
      assignedSite: 'ਨਿਰਧਾਰਤ ਸਾਈਟ',
      dutyStatus: 'ਡਿਊਟੀ ਸਥਿਤੀ',
      notAvailable: 'ਉਪਲਬਧ ਨਹੀਂ',
      back: 'ਵਾਪਸ ਜਾਓ',
      editProfile: 'ਪ੍ਰੋਫ਼ਾਈਲ ਸੋਧੋ',
      employmentInformation: 'ਰੁਜ਼ਗਾਰ ਜਾਣਕਾਰੀ',
      age: 'ਉਮਰ',
      gender: 'ਲਿੰਗ',
      genderOptions: {
        male: 'ਪੁਰਸ਼',
        female: 'ਔਰਤ',
        other: 'ਹੋਰ',
      },
      cancel: 'ਰੱਦ ਕਰੋ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
      saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      profileUpdated: 'ਪ੍ਰੋਫ਼ਾਈਲ ਅੱਪਡੇਟ ਹੋਈ',
      profileUpdatedHint: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫ਼ਾਈਲ ਜਾਣਕਾਰੀ ਸੰਭਾਲ ਲਈ ਗਈ ਹੈ।',
      updateFailed: 'ਪ੍ਰੋਫ਼ਾਈਲ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ',
      idProof: 'ਪਛਾਣ ਪ੍ਰਮਾਣ',
      securityLicense: 'ਸੁਰੱਖਿਆ ਲਾਇਸੈਂਸ',
      certifications: 'ਸਰਟੀਫਿਕੇਟ',
      verified: 'ਤਸਦੀਕਸ਼ੁਦਾ',
      pending: 'ਲੰਬਿਤ',
      accountNumber: 'ਖਾਤਾ ਨੰਬਰ',
      ifscCode: 'IFSC ਕੋਡ',
      bankName: 'ਬੈਂਕ ਦਾ ਨਾਮ',
      contactName: 'ਸੰਪਰਕ ਨਾਮ',
      relationship: 'ਰਿਸ਼ਤਾ',
      contactPhone: 'ਸੰਪਰਕ ਫ਼ੋਨ',
      bankSaved: 'ਬੈਂਕ ਵੇਰਵੇ ਸੰਭਾਲੇ ਗਏ',
      bankSavedHint: 'ਤੁਹਾਡੇ ਬੈਂਕ ਵੇਰਵੇ ਸੰਭਾਲ ਲਏ ਗਏ ਹਨ।',
      emergencySaved: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਸੰਭਾਲਿਆ ਗਿਆ',
      emergencySavedHint: 'ਤੁਹਾਡਾ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਸੰਭਾਲ ਲਿਆ ਗਿਆ ਹੈ।',
      validation: {
        nameRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
        emailRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
        emailInvalid: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
        mobileInvalid: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
        ageInvalid: 'ਉਮਰ 18 ਤੋਂ 65 ਦੇ ਵਿਚਕਾਰ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
        accountNumberInvalid:
          'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ ਦਰਜ ਕਰੋ (9 ਤੋਂ 18 ਅੰਕ)।',
        ifscInvalid: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 11 ਅੱਖਰਾਂ ਦਾ IFSC ਕੋਡ ਦਰਜ ਕਰੋ।',
        bankNameRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਬੈਂਕ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
        contactNameRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਸੰਪਰਕ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
        relationshipRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਰਿਸ਼ਤਾ ਦਰਜ ਕਰੋ।',
        contactPhoneInvalid:
          'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10 ਅੰਕਾਂ ਦਾ ਸੰਪਰਕ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      },
      documentsEmpty: 'ਹਾਲੇ ਕੋਈ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ',
      documentsEmptyHint:
        'ਅੱਪਲੋਡ ਹੋਣ ’ਤੇ ਤੁਹਾਡੇ ਪਛਾਣ ਪੱਤਰ ਅਤੇ ਸਰਟੀਫਿਕੇਟ ਇੱਥੇ ਦਿਖਣਗੇ।',
      bankEmpty: 'ਹਾਲੇ ਕੋਈ ਬੈਂਕ ਵੇਰਵੇ ਨਹੀਂ',
      bankEmptyHint: 'ਤਨਖਾਹ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣੇ ਬੈਂਕ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ।',
      emergencyEmpty: 'ਹਾਲੇ ਕੋਈ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਨਹੀਂ',
      emergencyEmptyHint: 'ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਸੰਪਰਕ ਕਰਨ ਲਈ ਇੱਕ ਸੰਪਰਕ ਸ਼ਾਮਲ ਕਰੋ।',
      settingsEmpty: 'ਸੰਰਚਿਤ ਕਰਨ ਲਈ ਕੁਝ ਨਹੀਂ',
      settingsEmptyHint: 'ਐਪ ਤਰਜੀਹਾਂ ਅਤੇ ਸੈਟਿੰਗਾਂ ਇੱਥੇ ਦਿਖਣਗੀਆਂ।',
    },
    clientAgency: {
      guardsOnSite: 'ਸਾਈਟ ਉੱਤੇ ਗਾਰਡ',
      loadingGuards: 'ਨਿਯੁਕਤ ਗਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
      loadFailed: 'ਨਿਯੁਕਤ ਗਾਰਡ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      rateAgency: 'ਆਪਣੀ ਏਜੰਸੀ ਨੂੰ ਰੇਟ ਕਰੋ',
      feedbackPlaceholder: 'ਇਸ ਏਜੰਸੀ ਨਾਲ ਆਪਣਾ ਅਨੁਭਵ ਸਾਂਝਾ ਕਰੋ…',
      guardFeedbackPlaceholder: 'ਇਸ ਗਾਰਡ ਬਾਰੇ ਫੀਡਬੈਕ ਦਿਓ…',
      saveRating: 'ਰੇਟਿੰਗ ਸੇਵ ਕਰੋ',
      ratingSaved: 'ਰੇਟਿੰਗ ਸੇਵ ਹੋਈ',
      thankYou: 'ਤੁਹਾਡੇ ਫੀਡਬੈਕ ਲਈ ਧੰਨਵਾਦ।',
      unableToRate: 'ਰੇਟਿੰਗ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕੀ',
      noGuards: 'ਹਾਲੇ ਕੋਈ ਗਾਰਡ ਨਿਯੁਕਤ ਨਹੀਂ',
      noGuardsHint: 'ਏਜੰਸੀ ਵੱਲੋਂ ਨਿਯੁਕਤੀ ਪੂਰੀ ਹੋਣ ਉੱਤੇ ਗਾਰਡ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
      onSite: 'ਸਾਈਟ ਉੱਤੇ',
      overallRating: 'ਕੁੱਲ ਰੇਟਿੰਗ',
      rate: 'ਰੇਟ ਕਰੋ',
    },
    coverageManagement: {
      requests: 'ਕਲਾਇੰਟ ਬੇਨਤੀਆਂ',
      loading: 'ਕਲਾਇੰਟ ਬੇਨਤੀਆਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      loadFailed: 'ਕਲਾਇੰਟ ਬੇਨਤੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      noRequests: 'ਕੋਈ ਕਲਾਇੰਟ ਬੇਨਤੀ ਨਹੀਂ',
      noRequestsHint: 'ਨਵੀਆਂ ਕਵਰੇਜ ਬੇਨਤੀਆਂ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੀਆਂ।',
      requestDetails: 'ਬੇਨਤੀ ਵੇਰਵੇ',
      client: 'ਕਲਾਇੰਟ',
      event: 'ਸਾਈਟ ਜਾਂ ਸਮਾਗਮ',
      location: 'ਸਥਾਨ',
      guardsNeeded: 'ਲੋੜੀਂਦੇ ਗਾਰਡ',
      guardsCount: '{{count}} ਗਾਰਡ ਦੀ ਬੇਨਤੀ',
      guardsCount_other: '{{count}} ਗਾਰਡਾਂ ਦੀ ਬੇਨਤੀ',
      notes: 'ਨੋਟਸ',
      noNotes: 'ਕੋਈ ਨੋਟ ਨਹੀਂ ਦਿੱਤਾ',
      status: 'ਸਥਿਤੀ',
      assignGuards: 'ਗਾਰਡ ਨਿਯੁਕਤ ਕਰੋ',
      assignLimit: 'ਵੱਧ ਤੋਂ ਵੱਧ {{count}} ਉਪਲਬਧ ਗਾਰਡ ਚੁਣੋ।',
      selectGuardFirst: 'ਘੱਟੋ-ਘੱਟ ਇੱਕ ਉਪਲਬਧ ਗਾਰਡ ਚੁਣੋ।',
      noAvailableGuards: 'ਇਸ ਵੇਲੇ ਕੋਈ ਆਫ-ਡਿਊਟੀ ਗਾਰਡ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      approve: 'ਮਨਜ਼ੂਰ ਕਰੋ',
      reject: 'ਰੱਦ ਕਰੋ',
      assignSelected: 'ਚੁਣੇ ਗਾਰਡ ਨਿਯੁਕਤ ਕਰੋ',
      markCompleted: 'ਪੂਰਾ ਚਿੰਨ੍ਹਿਤ ਕਰੋ',
      requestUpdated: 'ਬੇਨਤੀ ਅੱਪਡੇਟ ਹੋਈ',
      requestUpdatedHint: 'ਕਲਾਇੰਟ ਬੇਨਤੀ ਦੀ ਸਥਿਤੀ ਸੇਵ ਹੋ ਗਈ ਹੈ।',
      unableToUpdate: 'ਬੇਨਤੀ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ',
      statuses: {
        pending: 'ਬਕਾਇਆ',
        approved: 'ਮਨਜ਼ੂਰ',
        rejected: 'ਰੱਦ',
        assigned: 'ਨਿਯੁਕਤ',
        completed: 'ਪੂਰਾ',
      },
    },
    addGuardForm: {
      title: 'ਗਾਰਡ ਜੋੜੋ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      email: 'ਈਮੇਲ',
      password: 'ਪਾਸਵਰਡ',
      joiningDate: 'ਨਿਯੁਕਤੀ ਦੀ ਮਿਤੀ',
      address: 'ਪਤਾ (ਵਿਕਲਪਿਕ)',
      age: 'ਉਮਰ (ਵਿਕਲਪਿਕ)',
      gender: 'ਲਿੰਗ (ਵਿਕਲਪਿਕ)',
      male: 'ਮਰਦ',
      female: 'ਔਰਤ',
      other: 'ਹੋਰ',
      site: 'ਸ਼ੁਰੂਆਤੀ ਸਾਈਟ ਨਿਯੁਕਤੀ',
      unassigned: 'ਅਣਨਿਯੁਕਤ',
      loadingSites: 'ਸਾਈਟਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      siteError:
        'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋਈਆਂ। ਬਿਨਾਂ ਸਾਈਟ ਗਾਰਡ ਜੋੜੋ ਜਾਂ ਫਾਰਮ ਮੁੜ ਖੋਲ੍ਹੋ।',
      coveragePlan: 'ਕਵਰੇਜ ਯੋਜਨਾ',
      day_shift: 'ਦਿਨ ਦੀ ਸ਼ਿਫਟ',
      night_watch: 'ਰਾਤ ਦੀ ਸ਼ਿਫਟ',
      '24x7': '24×7 ਕਵਰੇਜ',
      shiftHours: 'ਸ਼ਿਫਟ ਦੀ ਮਿਆਦ',
      hours: 'ਘੰਟੇ',
      startTime: 'ਸ਼ੁਰੂ ਸਮਾਂ',
      endTime: 'ਸਮਾਪਤੀ ਸਮਾਂ',
      endHint:
        'ਸਮਾਪਤੀ ਸਮਾਂ ਚੁਣੀ ਮਿਆਦ ਅਨੁਸਾਰ ਨਿਰਧਾਰਤ ਹੁੰਦਾ ਹੈ, ਰਾਤ ਦੀ ਸ਼ਿਫਟ ਸਮੇਤ।',
      coverageHint:
        '24×7 ਕਵਰੇਜ ਵਾਰੀ-ਵਾਰੀ ਸ਼ਿਫਟਾਂ ਵਰਤਦੀ ਹੈ; ਇੱਥੇ ਵੱਖਰੀ ਸ਼ਿਫਟ ਮਿਆਦ ਨਹੀਂ ਦਿੱਤੀ ਜਾਂਦੀ।',
      basicSalary: 'ਮੂਲ ਤਨਖਾਹ (ਵਿਕਲਪਿਕ)',
      allowances: 'ਭੱਤੇ (ਵਿਕਲਪਿਕ)',
      requiredHint: '* ਵਾਲੇ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹਨ।',
      requiredError: 'ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      contactError:
        'ਵੈਧ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ, ਈਮੇਲ ਅਤੇ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ।',
      dateError: 'ਵੈਧ ਮਿਤੀ YYYY-MM-DD ਵਿੱਚ ਦਰਜ ਕਰੋ।',
      ageError: 'ਉਮਰ 18 ਤੋਂ 65 ਵਿਚਕਾਰ ਪੂਰਾ ਅੰਕ ਹੋਵੇ।',
      salaryError: 'ਤਨਖਾਹ ਅਤੇ ਭੱਤੇ ਸਿਫ਼ਰ ਜਾਂ ਵੱਧ, ਦੋ ਦਸ਼ਮਲਵ ਅੰਕਾਂ ਤੱਕ ਦਰਜ ਕਰੋ।',
      success: 'ਗਾਰਡ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ।',
      failure: 'ਗਾਰਡ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      search: 'ਵਿਕਲਪ ਖੋਜੋ',
      noResults: 'ਕੋਈ ਵਿਕਲਪ ਨਹੀਂ ਮਿਲਿਆ।',
      close: 'ਬੰਦ ਕਰੋ',
    },
    common: {
      next: 'ਅੱਗੇ',
      back: 'ਵਾਪਸ',
      continue: 'ਜਾਰੀ ਰੱਖੋ',
      getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    },

    auth: {
      welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
      login: 'ਲਾਗ ਇਨ',
      createAccount: 'ਖਾਤਾ ਬਣਾਓ',
      forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?',
      enterValidIdentifier: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      couldNotSendOtp: 'OTP ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ',
      identifierPlaceholder: 'ਈਮੇਲ ਜਾਂ +91 ਮੋਬਾਈਲ ਨੰਬਰ',
      passwordChanged: 'ਤੁਹਾਡਾ ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲਿਆ ਗਿਆ ਹੈ।',
      invalidOtp: 'ਗਲਤ OTP',
      completeOtp: 'ਪੂਰਾ 6 ਅੰਕਾਂ ਦਾ ਪੁਸ਼ਟੀ ਕੋਡ ਦਰਜ ਕਰੋ।',
      verificationFailed: 'ਪੁਸ਼ਟੀ ਅਸਫਲ',
      identifierFallback: 'ਤੁਹਾਡਾ ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ',
      otpDigit: 'OTP ਅੰਕ {{number}}',
      mobileOtpDigit: 'ਮੋਬਾਈਲ ਪੁਸ਼ਟੀ ਅੰਕ {{number}}',
      loginSubtitle: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਲਾਗ ਇਨ ਕਰੋ',
      emailAddress: 'ਈਮੇਲ ਪਤਾ',
      password: 'ਪਾਸਵਰਡ',
      enterPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      showPassword: 'ਪਾਸਵਰਡ ਦਿਖਾਓ',
      hidePassword: 'ਪਾਸਵਰਡ ਲੁਕਾਓ',
      loggingIn: 'ਲਾਗ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
      orContinueWith: 'ਜਾਂ ਇਸ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      signUp: 'ਸਾਈਨ ਅੱਪ ਕਰੋ',
      invalidDetails: 'ਗਲਤ ਜਾਣਕਾਰੀ',
      enterLinkedEmail: 'ਆਪਣੇ ਖਾਤੇ ਨਾਲ ਜੁੜਿਆ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      invalidPassword: 'ਗਲਤ ਪਾਸਵਰਡ',
      loginFailed: 'ਲਾਗ ਇਨ ਅਸਫਲ',
      tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      createSubtitle: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਜਾਣਕਾਰੀ ਭਰੋ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      exampleName: 'ਜਿਵੇਂ ਆਕਾਸ਼ ਸਿੰਘ',
      alreadyAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
      invalidName: 'ਗਲਤ ਨਾਮ',
      enterFullName: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      invalidEmail: 'ਗਲਤ ਈਮੇਲ ਪਤਾ',
      enterValidEmail: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      passwordsMismatch: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
      passwordsMismatchMessage: 'ਪਾਸਵਰਡ ਅਤੇ ਪੁਸ਼ਟੀ ਇੱਕੋ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
      accountFailed: 'ਖਾਤਾ ਨਹੀਂ ਬਣ ਸਕਿਆ',
      backToSuperAdmin: 'ਸੁਪਰ ਐਡਮਿਨ ਵੱਲ ਵਾਪਸ',
      goBack: 'ਵਾਪਸ ਜਾਓ',
      forgotTitle: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
      emailOrMobile: 'ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ',
      rememberPassword: 'ਪਾਸਵਰਡ ਯਾਦ ਹੈ?',
      sendOtp: 'OTP ਭੇਜੋ',
      sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      forgotSubtitle: 'ਆਪਣਾ ਰਜਿਸਟਰਡ ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      verifyMobile: 'ਮੋਬਾਈਲ ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      verifyOtp: 'OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      enterCodeSent: 'ਭੇਜਿਆ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
      didNotReceive: 'OTP ਨਹੀਂ ਮਿਲਿਆ?',
      resendOtp: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      resendIn: '00:30 ਵਿੱਚ',
      verifyContinue: 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ',
      verifying: 'ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ...',
      couldNotResend: 'OTP ਦੁਬਾਰਾ ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ',
      newPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ',
      enterNewPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      confirmNewPassword: 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      newPasswordSubtitle: 'ਆਪਣਾ ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      resetPassword: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
      resetting: 'ਰੀਸੈੱਟ ਹੋ ਰਿਹਾ ਹੈ...',
      passwordUpdated: 'ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਇਆ!',
      passwordUpdatedMessage:
        'ਤੁਹਾਡਾ ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਹੋ ਗਿਆ ਹੈ। ਹੁਣ ਨਵੇਂ ਪਾਸਵਰਡ ਨਾਲ ਲਾਗ ਇਨ ਕਰੋ।',
      goToLogin: 'ਲਾਗ ਇਨ ਤੇ ਜਾਓ',
      invalidMobile: 'ਗਲਤ ਮੋਬਾਈਲ ਨੰਬਰ',
      enterValidMobile: 'ਸਹੀ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      confirmMustMatch: 'ਪੁਸ਼ਟੀ ਪਾਸਵਰਡ ਨਾਲ ਮਿਲਣੀ ਚਾਹੀਦੀ ਹੈ।',
      accountType: 'ਖਾਤਾ ਕਿਸਮ',
      chooseAccountType: 'ਆਪਣੀ ਖਾਤਾ ਕਿਸਮ ਚੁਣੋ...',
      agency: 'ਏਜੰਸੀ',
      client: 'ਕਲਾਇੰਟ',
      agencyDescription: 'ਗਾਰਡ ਅਤੇ ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ\nਸੰਭਾਲੋ',
      clientDescription: 'ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ ਲਵੋ ਅਤੇ\nਸੰਭਾਲੋ',
      creatingAccount: 'ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    },
    onboarding: {
      step1: {
        title: 'ਲੋਕ ਸੁਰੱਖਿਅਤ,\nਥਾਵਾਂ ਸੁਰੱਖਿਅਤ।',
        subtitle: 'ਪੇਸ਼ੇਵਰ ਸੁਰੱਖਿਆ ਪ੍ਰਬੰਧਨ ਹੁਣ ਸਰਲ, ਭਰੋਸੇਯੋਗ ਅਤੇ ਕੁਸ਼ਲ।',
      },
      step2: {
        title: 'ਕਦੇ ਵੀ, ਕਿਤੇ ਵੀ ਪ੍ਰਬੰਧ ਕਰੋ',
        subtitle: 'ਤੁਸੀਂ ਜਿੱਥੇ ਵੀ ਹੋਵੋ, ਆਪਣੇ ਸੁਰੱਖਿਆ ਕਾਰਜਾਂ ਨਾਲ ਜੁੜੇ ਰਹੋ।',
      },
      step3: {
        title: 'ਸੁਚੇਤ ਰਹੋ, ਤੇਜ਼ੀ ਨਾਲ ਜਵਾਬ ਦਿਓ।',
        subtitle: 'ਅੱਪਡੇਟ ਲਵੋ ਅਤੇ ਘਟਨਾਵਾਂ ਦਾ ਬਿਨਾਂ ਦੇਰੀ ਜਵਾਬ ਦਿਓ।',
      },
    },
    superAdmin: {
      agencies: 'ਏਜੰਸੀਆਂ',
      approvals: 'ਮਨਜ਼ੂਰੀਆਂ',
      liveStatus: 'ਲਾਈਵ ਸਥਿਤੀ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      addAgency: 'ਨਵੀਂ ਏਜੰਸੀ ਜੋੜੋ',
      searchAgencies: 'ਨਾਮ ਨਾਲ ਏਜੰਸੀ ਖੋਜੋ',
      active: 'ਸਰਗਰਮ',
      inactive: 'ਗੈਰ-ਸਰਗਰਮ',
      guards: 'ਗਾਰਡ',
      clients: 'ਕਲਾਇੰਟ',
      loadingAgencies: 'ਏਜੰਸੀਆਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ',
      unableAgencies: 'ਏਜੰਸੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      noMatching: 'ਕੋਈ ਮਿਲਦੀ ਏਜੰਸੀ ਨਹੀਂ',
      noInactive: 'ਕੋਈ ਗੈਰ-ਸਰਗਰਮ ਏਜੰਸੀ ਨਹੀਂ',
      noActive: 'ਹਾਲੇ ਕੋਈ ਸਰਗਰਮ ਏਜੰਸੀ ਨਹੀਂ',
      searchHint: 'ਹੋਰ ਏਜੰਸੀ ਨਾਮ ਖੋਜੋ ਜਾਂ ਸਥਿਤੀ ਫਿਲਟਰ ਬਦਲੋ।',
      approvalHint: 'ਮਨਜ਼ੂਰ ਏਜੰਸੀਆਂ ਸੁਪਰ ਐਡਮਿਨ ਸਮੀਖਿਆ ਤੋਂ ਬਾਅਦ ਇੱਥੇ ਦਿਖਣਗੀਆਂ।',
      networkTitle: 'ਤੁਹਾਡਾ ਨੈੱਟਵਰਕ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ',
      liveUnavailable: 'ਲਾਈਵ ਰਿਪੋਰਟਿੰਗ ਹਾਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      agencyApprovals: 'ਏਜੰਸੀ ਮਨਜ਼ੂਰੀਆਂ',
      refreshRequests: 'ਬੇਨਤੀਆਂ ਤਾਜ਼ਾ ਕਰੋ',
      noPending: 'ਕੋਈ ਏਜੰਸੀ ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਵਿੱਚ ਨਹੀਂ ਹੈ।',
      approve: 'ਮਨਜ਼ੂਰ ਕਰੋ',
      reject: 'ਰੱਦ ਕਰੋ',
      notifications: 'ਸੂਚਨਾਵਾਂ',
      markAllRead: 'ਸਭ ਪੜ੍ਹੀਆਂ ਕਰੋ',
      reviewApprovals: 'ਏਜੰਸੀ ਮਨਜ਼ੂਰੀਆਂ ਵੇਖੋ',
      loadingNotifications: 'ਸੂਚਨਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      tryAgain: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      noNotifications: 'ਹਾਲੇ ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ',
      deleteNotification: 'ਸੂਚਨਾ ਹਟਾਉਣੀ ਹੈ?',
      deleteNotificationMessage: 'ਇਹ ਸੂਚਨਾ ਹਟਾ ਦਿੱਤੀ ਜਾਵੇਗੀ।',
      delete: 'ਹਟਾਓ',
      cancel: 'ਰੱਦ ਕਰੋ',
      loadingProfile: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…',
      profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
      photoSoon: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅੱਪਲੋਡ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗਾ।',
      yourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ',
      accountId: 'ਖਾਤਾ ਆਈਡੀ: {{id}}',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      email: 'ਈਮੇਲ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      saveChanges: 'ਬਦਲਾਅ ਸੰਭਾਲੋ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profileUpdated: 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਹੋਈ',
      changesSaved: 'ਤੁਹਾਡੇ ਬਦਲਾਅ ਸੰਭਾਲੇ ਗਏ ਹਨ।',
      fullNameRequired: 'ਪੂਰਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterFullName: 'ਸੁਪਰ ਐਡਮਿਨ ਦਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      invalidEmail: 'ਗਲਤ ਈਮੇਲ',
      enterEmail: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      invalidPhone: 'ਗਲਤ ਫੋਨ ਨੰਬਰ',
      enterPhone: 'ਸਹੀ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      editAgency: 'ਏਜੰਸੀ ਸੋਧੋ',
      manageAgency: 'ਏਜੰਸੀ ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ ਸੰਭਾਲੋ',
      agencyDetails: 'ਏਜੰਸੀ ਵੇਰਵੇ',
      accountDetails: 'ਖਾਤਾ ਵੇਰਵੇ',
      businessDetails: 'ਕਾਰੋਬਾਰੀ ਵੇਰਵੇ',
      address: 'ਪਤਾ',
      status: 'ਸਥਿਤੀ',
      leavePassword: 'ਮੌਜੂਦਾ ਰੱਖਣ ਲਈ ਖਾਲੀ ਛੱਡੋ',
      removeAgency: 'ਏਜੰਸੀ ਹਟਾਓ',
      agencyUpdated: 'ਏਜੰਸੀ ਅੱਪਡੇਟ ਹੋਈ',
      agencySaved: 'ਏਜੰਸੀ ਦੀ ਜਾਣਕਾਰੀ ਸੰਭਾਲੀ ਗਈ ਹੈ।',
      loadingLocations: 'ਥਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      closeEditor: 'ਏਜੰਸੀ ਸੋਧਕ ਬੰਦ ਕਰੋ',
    },
    details: {
      agencyTitle: 'ਏਜੰਸੀ ਵੇਰਵੇ',
      agencySubtitle: 'ਆਪਣੀ ਏਜੰਸੀ ਬਾਰੇ ਦੱਸੋ',
      agencyName: 'ਏਜੰਸੀ / ਕੰਪਨੀ ਦਾ ਨਾਮ',
      enterAgencyName: 'ਏਜੰਸੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      businessType: 'ਕਾਰੋਬਾਰ ਦੀ ਕਿਸਮ',
      gstNumber: 'GST ਨੰਬਰ (ਵਿਕਲਪਿਕ)',
      enterGst: 'GST ਨੰਬਰ ਦਰਜ ਕਰੋ',
      officeAddress: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ',
      enterOfficeAddress: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      clientTitle: 'ਕਲਾਇੰਟ ਵੇਰਵੇ',
      clientSubtitle: 'ਆਪਣੀ ਸੰਸਥਾ ਬਾਰੇ ਦੱਸੋ',
      companyName: 'ਕੰਪਨੀ / ਸੰਸਥਾ ਦਾ ਨਾਮ',
      enterCompanyName: 'ਕੰਪਨੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteName: 'ਸਾਈਟ / ਜਾਇਦਾਦ ਦਾ ਨਾਮ',
      enterSiteName: 'ਸਾਈਟ/ਜਾਇਦਾਦ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ',
      enterSiteAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      enterCity: 'ਸ਼ਹਿਰ ਦਰਜ ਕਰੋ',
      selectState: 'ਰਾਜ ਚੁਣੋ',
      enterPincode: 'ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ',
      loadingLocations: 'ਥਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      closeLocations: 'ਥਾਂ ਵਿਕਲਪ ਬੰਦ ਕਰੋ',
      agencyNameRequired: 'ਏਜੰਸੀ ਦਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterAgencyCompany: 'ਆਪਣੀ ਏਜੰਸੀ ਜਾਂ ਕੰਪਨੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      businessRequired: 'ਕਾਰੋਬਾਰ ਕਿਸਮ ਲਾਜ਼ਮੀ ਹੈ',
      selectBusiness: 'ਆਪਣੀ ਕਾਰੋਬਾਰ ਕਿਸਮ ਚੁਣੋ।',
      officeRequired: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
      enterOffice: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ।',
      cityRequired: 'ਸ਼ਹਿਰ ਲਾਜ਼ਮੀ ਹੈ',
      enterYourCity: 'ਆਪਣਾ ਸ਼ਹਿਰ ਦਰਜ ਕਰੋ।',
      stateRequired: 'ਰਾਜ ਲਾਜ਼ਮੀ ਹੈ',
      selectStateTerritory: 'ਆਪਣਾ ਰਾਜ ਜਾਂ ਕੇਂਦਰ ਸ਼ਾਸਿਤ ਪ੍ਰਦੇਸ਼ ਚੁਣੋ।',
      districtRequired: 'ਜ਼ਿਲ੍ਹਾ ਲਾਜ਼ਮੀ ਹੈ',
      selectDistrict: 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ।',
      invalidPincode: 'ਗਲਤ ਪਿੰਨਕੋਡ',
      enterValidPincode: 'ਸਹੀ 6 ਅੰਕਾਂ ਦਾ ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ।',
      siteNameRequired: 'ਸਾਈਟ ਦਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterProperty: 'ਆਪਣੀ ਸਾਈਟ ਜਾਂ ਜਾਇਦਾਦ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      siteAddressRequired: 'ਸਾਈਟ ਦਾ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
      enterAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ।',
    },
    client: {
      home: 'ਹੋਮ',
      request: 'ਬੇਨਤੀ',
      invoices: 'ਇਨਵੌਇਸ',
      alerts: 'ਅਲਰਟ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      portal: 'ਕਲਾਇੰਟ ਪੋਰਟਲ',
      loading: 'ਕਲਾਇੰਟ ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
      loadFailed: 'ਕਲਾਇੰਟ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      yourAgencies: 'ਤੁਹਾਡੀਆਂ ਏਜੰਸੀਆਂ',
      noAgency: 'ਕੋਈ ਏਜੰਸੀ ਨਿਯੁਕਤ ਨਹੀਂ ਹੈ',
      noAgencyHint: 'ਤੁਹਾਡੀ ਨਿਯੁਕਤ ਸੁਰੱਖਿਆ ਏਜੰਸੀ ਇੱਥੇ ਦਿਖੇਗੀ।',
      coveragePlan: 'ਕਵਰੇਜ ਯੋਜਨਾ',
      noCoverage: 'ਕੋਈ ਕਵਰੇਜ ਯੋਜਨਾ ਨਹੀਂ',
      noCoverageHint: 'ਏਜੰਸੀ ਨਿਯੁਕਤ ਹੋਣ ਤੇ ਕਵਰੇਜ ਵੇਰਵੇ ਇੱਥੇ ਦਿਖਣਗੇ।',
      requestCoverage: 'ਸੁਰੱਖਿਆ ਕਵਰੇਜ ਦੀ ਬੇਨਤੀ ਕਰੋ',
      requestHint: 'ਕਵਰੇਜ ਬੇਨਤੀ ਸਹੂਲਤ ਇੱਥੇ ਦਿਖੇਗੀ।',
      noInvoices: 'ਕੋਈ ਇਨਵੌਇਸ ਨਹੀਂ',
      noInvoicesHint: 'ਉਪਲਬਧ ਹੋਣ ਤੇ ਤੁਹਾਡੇ ਇਨਵੌਇਸ ਇੱਥੇ ਦਿਖਣਗੇ।',
      noAlerts: 'ਕੋਈ ਅਲਰਟ ਨਹੀਂ',
      noAlertsHint: 'ਸੁਰੱਖਿਆ ਅਤੇ ਖਾਤਾ ਅਲਰਟ ਇੱਥੇ ਦਿਖਣਗੇ।',
      noAgencyYet: 'ਹਾਲੇ ਕੋਈ ਏਜੰਸੀ ਨਹੀਂ',
      noAgencyYetHint:
        'ਤੁਸੀਂ ਹਾਲੇ ਕੋਈ ਏਜੰਸੀ ਨਹੀਂ ਰੱਖੀ। ਏਜੰਸੀ ਲੱਭਣ ਅਤੇ ਕਵਰੇਜ ਬੇਨਤੀ ਭੇਜਣ ਲਈ ਬੇਨਤੀ ਟੈਬ ਵਰਤੋ।',
      helpfulInformation: 'ਮਦਦਗਾਰ ਜਾਣਕਾਰੀ',
      howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ?',
      howItWorksHint: 'ਕਵਰੇਜ ਦੀ ਬੇਨਤੀ ਅਤੇ ਪ੍ਰਬੰਧਨ ਕਰਨਾ ਸਿੱਖੋ',
      whyHireAgency: 'ਏਜੰਸੀ ਕਿਉਂ ਰੱਖੀਏ?',
      whyHireAgencyHint: 'ਪੇਸ਼ੇਵਰ ਅਤੇ ਭਰੋਸੇਯੋਗ ਸੁਰੱਖਿਆ ਪ੍ਰਾਪਤ ਕਰੋ',
      needHelp: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
      needHelpHint: 'ਸਾਡੀ ਸਹਾਇਤਾ ਟੀਮ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
      securityQuote: '“ਸੁਰੱਖਿਅਤ ਥਾਵਾਂ, ਮਜ਼ਬੂਤ ਕਾਰੋਬਾਰ।”',
      welcomeBack: 'ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ!',
      securityOverview: 'ਇਹ ਤੁਹਾਡੀ ਸੁਰੱਖਿਆ ਕਵਰੇਜ ਦੀ ਝਲਕ ਹੈ।',
      securityPartner: 'ਤੁਹਾਡਾ ਸੁਰੱਖਿਆ ਸਾਥੀ',
      activeCoverage: 'ਸਰਗਰਮ ਕਵਰੇਜ',
      guardsAssigned: '{{count}} ਗਾਰਡ ਨਿਯੁਕਤ',
      guardsAssigned_other: '{{count}} ਗਾਰਡ ਨਿਯੁਕਤ',
      active: 'ਸਰਗਰਮ',
    },
    clientInfo: {
      back: 'ਵਾਪਸ',
      howItWorksIntro: 'ਪੇਸ਼ੇਵਰ ਸੁਰੱਖਿਆ ਕਵਰੇਜ ਦੀ ਬੇਨਤੀ ਕਰਨਾ ਆਸਾਨ ਹੈ।',
      whyHireIntro: 'ਪੇਸ਼ੇਵਰ ਸੁਰੱਖਿਆ ਏਜੰਸੀ ਨਾਲ ਕੰਮ ਕਰਨ ਦੇ ਲਾਭ।',
      chooseLocation: 'ਆਪਣਾ ਸਥਾਨ ਚੁਣੋ',
      chooseLocationBody:
        'ਉਹ ਰਾਜ, ਜ਼ਿਲ੍ਹਾ, ਸ਼ਹਿਰ ਅਤੇ ਸਹੀ ਸਾਈਟ ਚੁਣੋ ਜਿੱਥੇ ਸੁਰੱਖਿਆ ਚਾਹੀਦੀ ਹੈ।',
      selectAgency: 'ਏਜੰਸੀ ਦੀ ਸਮੀਖਿਆ ਕਰਕੇ ਚੁਣੋ',
      selectAgencyBody:
        'ਆਪਣੇ ਜ਼ਿਲ੍ਹੇ ਦੀਆਂ ਮਨਜ਼ੂਰ ਏਜੰਸੀਆਂ ਦੀ ਤੁਲਨਾ ਕਰੋ ਅਤੇ ਵੇਰਵੇ ਦੇਖੋ।',
      sendRequest: 'ਆਪਣੀ ਬੇਨਤੀ ਭੇਜੋ',
      sendRequestBody: 'ਲੋੜੀਂਦੇ ਗਾਰਡ ਅਤੇ ਜ਼ਰੂਰਤਾਂ ਦਰਜ ਕਰਕੇ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ।',
      trackCoverage: 'ਕਵਰੇਜ ਦੀ ਸਥਿਤੀ ਵੇਖੋ',
      trackCoverageBody: 'ਬੇਨਤੀ ਦੀ ਸਥਿਤੀ ਅਤੇ ਸਰਗਰਮ ਕਵਰੇਜ ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਵੇਖੋ।',
      verifiedSecurity: 'ਤਸਦੀਕਸ਼ੁਦਾ ਸੁਰੱਖਿਆ ਪ੍ਰਦਾਤਾ',
      verifiedSecurityBody:
        'ਪਲੇਟਫਾਰਮ ਦੁਆਰਾ ਜਾਂਚੀਆਂ ਅਤੇ ਮਨਜ਼ੂਰ ਏਜੰਸੀਆਂ ਵਿੱਚੋਂ ਚੁਣੋ।',
      trainedGuards: 'ਪੇਸ਼ੇਵਰ ਢੰਗ ਨਾਲ ਪ੍ਰਬੰਧਿਤ ਗਾਰਡ',
      trainedGuardsBody:
        'ਏਜੰਸੀਆਂ ਗਾਰਡ ਨਿਯੁਕਤੀ, ਸ਼ਿਫਟਾਂ ਅਤੇ ਸਾਈਟ ਲੋੜਾਂ ਸੰਭਾਲਦੀਆਂ ਹਨ।',
      reliableCoverage: 'ਭਰੋਸੇਯੋਗ ਕਵਰੇਜ',
      reliableCoverageBody:
        'ਆਪਣੀ ਸਾਈਟ ਜਾਂ ਸਮਾਗਮ ਲਈ ਲੋੜੀਂਦੇ ਗਾਰਡਾਂ ਦੀ ਬੇਨਤੀ ਕਰੋ।',
      clearRecords: 'ਸਪਸ਼ਟ ਡਿਜੀਟਲ ਰਿਕਾਰਡ',
      clearRecordsBody: 'ਬੇਨਤੀਆਂ, ਕਵਰੇਜ, ਇਨਵੌਇਸ ਅਤੇ ਅਲਰਟ ਵਿਵਸਥਿਤ ਰੱਖੋ।',
      requestNote: 'ਤੁਸੀਂ ਬੇਨਤੀ ਟੈਬ ਤੋਂ ਕਿਸੇ ਵੀ ਸਮੇਂ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ।',
      partnerNote: 'ਕਵਰੇਜ ਬੇਨਤੀ ਦੀ ਪੁਸ਼ਟੀ ਤੋਂ ਪਹਿਲਾਂ ਏਜੰਸੀ ਦੇ ਵੇਰਵੇ ਵੇਖੋ।',
      supportSubject: 'ਸੈਂਟਰੀ ਸਿਕਿਉਰਿਟੀ ਐਪ ਸਹਾਇਤਾ',
      emailUnavailable:
        'ਈਮੇਲ ਐਪ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। helpdesk@gmail.com ਤੇ ਸੰਪਰਕ ਕਰੋ।',
    },
    coverageRequest: {
      location: 'ਤੁਹਾਡੀ ਥਾਂ',
      eventName: 'ਸਮਾਗਮ ਦਾ ਨਾਮ',
      eventPlaceholder: 'ਸਮਾਗਮ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteLocation: 'ਸਾਈਟ ਜਾਂ ਸਮਾਗਮ ਦੀ ਥਾਂ',
      sitePlaceholder: 'ਜਿਵੇਂ ਈਸਟ ਵਿੰਗ ਦਾਖਲਾ',
      guardsNeeded: 'ਲੋੜੀਂਦੇ ਗਾਰਡ',
      notes: 'ਨੋਟਸ',
      notesPlaceholder: 'ਮਿਤੀਆਂ, ਸ਼ਿਫਟ ਸਮਾਂ, ਖਾਸ ਲੋੜਾਂ…',
      send: 'ਬੇਨਤੀ ਭੇਜੋ',
      sending: 'ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ…',
      myRequests: 'ਮੇਰੀਆਂ ਬੇਨਤੀਆਂ',
      none: 'ਹਾਲੇ ਕੋਈ ਕਵਰੇਜ ਬੇਨਤੀ ਨਹੀਂ ਹੈ।',
      required: 'ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      sentTitle: 'ਬੇਨਤੀ ਭੇਜੀ ਗਈ',
      sentMessage: 'ਤੁਹਾਡੀ ਕਵਰੇਜ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਹੋ ਗਈ ਹੈ।',
      sendFailed: 'ਬੇਨਤੀ ਨਹੀਂ ਭੇਜੀ ਜਾ ਸਕੀ।',
      loadFailed: 'ਬੇਨਤੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      locationFailed: 'ਥਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      selectStateFirst: 'ਪਹਿਲਾਂ ਰਾਜ ਚੁਣੋ।',
      selectDistrictFirst: 'ਪਹਿਲਾਂ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ।',
      agenciesInArea: 'ਤੁਹਾਡੇ ਖੇਤਰ ਦੀਆਂ ਏਜੰਸੀਆਂ',
      noAgenciesInArea:
        'ਇਸ ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਅਜੇ ਕੋਈ ਏਜੰਸੀ ਨਹੀਂ ਮਿਲੀ — ਨੇੜਲਾ ਜ਼ਿਲ੍ਹਾ ਅਜ਼ਮਾਓ।',
      agenciesFailed: 'ਇਸ ਜ਼ਿਲ੍ਹੇ ਦੀਆਂ ਏਜੰਸੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      available: 'ਉਪਲਬਧ',
      selectAgency: 'ਚੁਣੋ',
      changeAgency: 'ਬਦਲੋ',
      agencyDetails: 'ਏਜੰਸੀ ਦੇ ਵੇਰਵੇ',
      agencyDetailsFailed: 'ਏਜੰਸੀ ਦੇ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      loadingAgencyDetails: 'ਏਜੰਸੀ ਦੇ ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
      serviceArea: 'ਸੇਵਾ ਖੇਤਰ',
      selectThisAgency: 'ਏਜੰਸੀ ਚੁਣੋ',
      status: {
        pending: 'ਲੰਬਿਤ',
        approved: 'ਮਨਜ਼ੂਰ',
        rejected: 'ਰੱਦ',
        assigned: 'ਨਿਯੁਕਤ',
        completed: 'ਪੂਰੀ',
        cancelled: 'ਰੱਦ ਕੀਤੀ',
      },
    },
    dashboard: {
      noNotificationsHint: 'ਤੁਹਾਡੀਆਂ ਸੂਚਨਾਵਾਂ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੀਆਂ।',
      dashboard: 'ਡੈਸ਼ਬੋਰਡ',
      overview: 'ਓਵਰਵਿਊ',
      guard: 'ਗਾਰਡ',
      sites: 'ਸਾਈਟਾਂ',
      incidents: 'ਘਟਨਾਵਾਂ',
      plan: 'ਪਲਾਨ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      quickSummary: 'ਤੁਰੰਤ ਸੰਖੇਪ',
      today: 'ਅੱਜ',
      guardsOnDuty: 'ਡਿਊਟੀ ਉੱਤੇ ਗਾਰਡ',
      activeSites: 'ਸਰਗਰਮ ਸਾਈਟਾਂ',
      openIncidents: 'ਖੁੱਲ੍ਹੀਆਂ ਘਟਨਾਵਾਂ',
      unassignedGuards: 'ਨਾ ਲਗਾਏ ਗਾਰਡ',
      viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
      payrollSummary: 'ਪੇਰੋਲ ਸੰਖੇਪ',
      invoices: 'ਇਨਵੌਇਸ',
      clientReviews: 'ਕਲਾਇੰਟ ਸਮੀਖਿਆਵਾਂ',
      quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      liveStatus: 'ਲਾਈਵ ਸਥਿਤੀ',
      viewAll: 'ਸਾਰੇ ਵੇਖੋ',
      onDuty: 'ਡਿਊਟੀ ਉੱਤੇ',
      addGuard: '+ ਗਾਰਡ',
      addSite: '+ ਸਾਈਟ ਜੋੜੋ',
      incident: 'ਘਟਨਾ',
      fileIncident: 'ਘਟਨਾ ਦਰਜ ਕਰੋ',
      searchSites: 'ਸਾਈਟਾਂ ਖੋਜੋ...',
      filter: 'ਫਿਲਟਰ',
      loadingSites: 'ਸਾਈਟਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noSites: 'ਕੋਈ ਸਾਈਟ ਨਹੀਂ ਮਿਲੀ।',
      loadingIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noIncidents: 'ਕੋਈ ਘਟਨਾ ਨਹੀਂ ਮਿਲੀ।',
      unableToLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      unableToLoadIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      site: 'ਸਾਈਟ',
      selectSite: 'ਸਾਈਟ ਚੁਣੋ',
      selectInitialSite: 'ਸ਼ੁਰੂਆਤੀ ਸਾਈਟ ਚੁਣੋ',
      selectJoiningDate: 'ਨਿਯੁਕਤੀ ਦੀ ਮਿਤੀ ਚੁਣੋ',
      year: 'ਸਾਲ',
      month: 'ਮਹੀਨਾ',
      date: 'ਮਿਤੀ',
      done: 'ਹੋ ਗਿਆ',
      showPassword: 'ਪਾਸਵਰਡ ਦਿਖਾਓ',
      hidePassword: 'ਪਾਸਵਰਡ ਲੁਕਾਓ',
      previousMonth: 'ਪਿਛਲਾ ਮਹੀਨਾ',
      nextMonth: 'ਅਗਲਾ ਮਹੀਨਾ',
      editGuard: 'ਗਾਰਡ ਸੋਧੋ',
      guardUpdated: 'ਗਾਰਡ ਦੀ ਜਾਣਕਾਰੀ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਈ।',
      newGuardPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ (ਵਿਕਲਪਿਕ)',
      leavePasswordBlank: 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ ਰੱਖਣ ਲਈ ਖਾਲੀ ਛੱਡੋ',
      removeGuard: 'ਗਾਰਡ ਹਟਾਓ',
      removeGuardConfirmation:
        'ਇਸ ਗਾਰਡ ਨੂੰ ਹਟਾਉਣਾ ਹੈ? ਉਹਨਾਂ ਦਾ ਲੌਗਇਨ ਬੰਦ ਹੋ ਜਾਵੇਗਾ। ਇਹ ਵਾਪਸ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।',
      cancel: 'ਰੱਦ ਕਰੋ',
      all: 'ਸਾਰੇ',
      severity: 'ਗੰਭੀਰਤਾ',
      low: 'ਘੱਟ',
      medium: 'ਦਰਮਿਆਨਾ',
      high: 'ਉੱਚ',
      notes: 'ਨੋਟਸ',
      describeIncident: 'ਕੀ ਹੋਇਆ, ਵੇਰਵਾ ਦਿਓ...',
      uploadPhotos: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
      optional: '(ਵਿਕਲਪਿਕ)',
      addPhotos: 'ਫੋਟੋ ਜੋੜੋ',
      maxPhotos: 'ਵੱਧ ਤੋਂ ਵੱਧ 5 ਫੋਟੋਆਂ, ਹਰ ਇੱਕ 10MB ਤੱਕ',
      filing: 'ਦਰਜ ਹੋ ਰਿਹਾ ਹੈ...',
      incidentFiled: 'ਘਟਨਾ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋਈ',
      incidentRecorded: 'ਤੁਹਾਡੀ ਘਟਨਾ ਦਰਜ ਕਰ ਲਈ ਗਈ ਹੈ ਅਤੇ ਸਮੀਖਿਆ ਕੀਤੀ ਜਾਵੇਗੀ।',
      siteName: 'ਸਾਈਟ ਦਾ ਨਾਮ',
      address: 'ਪਤਾ',
      enterSiteName: 'ਸਾਈਟ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      enterCompleteAddress: 'ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      startTyping: 'ਸੁਝਾਵਾਂ ਲਈ ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
      locationGps: 'ਟਿਕਾਣਾ (GPS)',
      noGps: 'ਕੋਈ GPS ਟਿਕਾਣਾ ਨਹੀਂ ਮਿਲਿਆ',
      useCurrentLocation: 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ ਵਰਤੋ',
      coveragePlan: 'ਕਵਰੇਜ ਪਲਾਨ',
      dayShift: 'ਦਿਨ ਦੀ ਸ਼ਿਫਟ',
      nightWatch: 'ਰਾਤ ਦੀ ਨਿਗਰਾਨੀ',
      coverage24x7: '24×7 ਕਵਰੇਜ',
      startTime: 'ਸ਼ੁਰੂਆਤੀ ਸਮਾਂ',
      endTime: 'ਅੰਤ ਸਮਾਂ',
      saveSite: 'ਸਾਈਟ ਸੇਵ ਕਰੋ',
      saving: 'ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ...',
      addressNotProvided: 'ਪਤਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      guardDataUnavailable: 'ਗਾਰਡ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      notSet: 'ਸੈੱਟ ਨਹੀਂ ਹੈ',
      notScheduled: 'ਨਿਰਧਾਰਤ ਨਹੀਂ ਹੈ',
      myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      settings: 'ਸੈਟਿੰਗਾਂ',
      language: 'ਭਾਸ਼ਾ',
      appearance: 'ਦਿੱਖ',
      light: 'ਲਾਈਟ',
      dark: 'ਡਾਰਕ',
      system: 'ਸਿਸਟਮ',
      logOut: 'ਲੌਗ ਆਉਟ',
      english: 'ਅੰਗਰੇਜ਼ੀ',
      hindi: 'ਹਿੰਦੀ',
      punjabi: 'ਪੰਜਾਬੀ',
      missingDetails: 'ਵੇਰਵੇ ਅਧੂਰੇ ਹਨ',
      selectSiteAndDescribe: 'ਸਾਈਟ ਚੁਣੋ ਅਤੇ ਘਟਨਾ ਦਾ ਵੇਰਵਾ ਦਿਓ।',
      siteAndAddressRequired: 'ਸਾਈਟ ਦਾ ਨਾਮ ਅਤੇ ਪਤਾ ਲਾਜ਼ਮੀ ਹਨ।',
      couldNotFile: 'ਘਟਨਾ ਦਰਜ ਨਹੀਂ ਹੋ ਸਕੀ',
      couldNotLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ',
      tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      photoUploadSoon: 'ਫੋਟੋ ਅੱਪਲੋਡ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
      gpsSoon: 'GPS ਟਿਕਾਣਾ ਸਹੂਲਤ ਜਲਦੀ ਜੋੜੀ ਜਾਵੇਗੀ।',
      close: 'ਬੰਦ ਕਰੋ',
      tapGuardDetails: 'ਗਾਰਡ ਦੇ ਵੇਰਵੇ ਦੇਖਣ ਜਾਂ ਸੋਧਣ ਲਈ ਟੈਪ ਕਰੋ',
      loadingGuards: 'ਗਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
      noGuardsOnDuty: 'ਇਸ ਵੇਲੇ ਕੋਈ ਗਾਰਡ ਡਿਊਟੀ ਉੱਤੇ ਨਹੀਂ ਹੈ।',
      unableToLoadGuards: 'ਗਾਰਡ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      unassignedSite: 'ਨਾ ਲਗਾਈ ਸਾਈਟ',
      live: 'ਲਾਈਵ',
      noLocationYet: 'ਹਾਲੇ ਕੋਈ ਟਿਕਾਣਾ ਨਹੀਂ',
      tapSiteManage: 'ਸਾਈਟਾਂ ਟੈਬ ਵਿੱਚ ਪ੍ਰਬੰਧਨ ਲਈ ਸਾਈਟ ਉੱਤੇ ਟੈਪ ਕਰੋ',
      active: 'ਸਰਗਰਮ',
      guardCount: '{{count}} ਗਾਰਡ',
      agencyAdmin: 'ਏਜੰਸੀ ਐਡਮਿਨ',
      accountDetails: 'ਖਾਤੇ ਦੇ ਵੇਰਵੇ',
      yourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      emailAddress: 'ਈਮੇਲ ਪਤਾ',
      state: 'ਰਾਜ',
      district: 'ਜ਼ਿਲ੍ਹਾ',
      city: 'ਸ਼ਹਿਰ',
      pincode: 'ਪਿੰਨਕੋਡ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
      loadingProfile: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
      profileRequired: 'ਖਾਤੇ ਦੇ ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      changesSaved: 'ਤੁਹਾਡੀਆਂ ਤਬਦੀਲੀਆਂ ਸੇਵ ਹੋ ਗਈਆਂ ਹਨ।',
      offlineAddressHint: 'ਆਫਲਾਈਨ ਹੋਣ ਤੇ ਪਤੇ ਦੇ ਸੁਝਾਅ ਉਪਲਬਧ ਨਹੀਂ ਹਨ।',
      rotateCoverage: '24 ਘੰਟਿਆਂ ਦੀ ਕਵਰੇਜ ਲਈ ਗਾਰਡ ਸ਼ਿਫਟਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।',
      selectedPlan: 'ਚੁਣਿਆ ਕਵਰੇਜ ਪਲਾਨ ਇਸ ਸਾਈਟ ਲਈ ਵਰਤਿਆ ਜਾਵੇਗਾ।',
      getDirections: 'ਦਿਸ਼ਾਵਾਂ ਲਵੋ',
      directionsUnavailable:
        'ਮੈਪ ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਜੁੜਨ ਤੋਂ ਬਾਅਦ ਦਿਸ਼ਾਵਾਂ ਉਪਲਬਧ ਹੋਣਗੀਆਂ।',
      removeSite: 'ਸਾਈਟ ਹਟਾਓ',
      removeSiteConfirm:
        'ਕੀ ਇਹ ਸਾਈਟ ਹਟਾਉਣੀ ਹੈ? ਮੌਜੂਦਾ ਗਾਰਡ ਨਿਯੁਕਤੀਆਂ ਪ੍ਰਭਾਵਿਤ ਹੋ ਸਕਦੀਆਂ ਹਨ।',
      siteUpdated: 'ਸਾਈਟ ਦੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਹੋ ਗਏ ਹਨ।',
      siteUpdateFailed: 'ਸਾਈਟ ਦੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੇ।',
      siteRemoved: 'ਸਾਈਟ ਹਟਾ ਦਿੱਤੀ ਗਈ ਹੈ।',
      siteRemoveFailed: 'ਸਾਈਟ ਹਟਾਈ ਨਹੀਂ ਜਾ ਸਕੀ।',
      siteUpdateUnavailable:
        'ਸਾਈਟ ਨੂੰ ਸੋਧਣ ਜਾਂ ਹਟਾਉਣ ਲਈ ਬੈਕਐਂਡ ਅਪਡੇਟ/ਡਿਲੀਟ ਐਂਡਪੌਇੰਟ ਦੀ ਲੋੜ ਹੈ।',
      searchGuards: 'ਨਾਮ, ਆਈਡੀ ਜਾਂ ਸਾਈਟ ਨਾਲ ਗਾਰਡ ਖੋਜੋ',
      offDuty: 'ਆਫ ਡਿਊਟੀ',
      noGuardsFound: 'ਕੋਈ ਗਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
      callGuard: 'ਗਾਰਡ ਨੂੰ ਕਾਲ ਕਰੋ',
      guardAddUnavailable: 'ਗਾਰਡ ਜੋੜਨ ਵਾਲਾ ਫਾਰਮ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
      noMatchingLocations: 'ਕੋਈ ਮਿਲਦੀ ਥਾਂ ਨਹੀਂ ਮਿਲੀ।',
    },
    guard: {
      tabs: {
        duty: 'ਡਿਊਟੀ',
        schedule: 'ਸ਼ਡਿਊਲ',
        patrol: 'ਗਸ਼ਤ',
        report: 'ਰਿਪੋਰਟ',
        profile: 'ਪ੍ਰੋਫਾਈਲ',
      },
      common: {
        guardFallback: 'ਗਾਰਡ',
        badgeId: 'ਬੈਜ ID {{id}}',
        closeProfileMenu: 'ਪ੍ਰੋਫਾਈਲ ਮੈਨੂ ਬੰਦ ਕਰੋ',
        featureSoon: 'ਇਹ ਗਾਰਡ ਸਹੂਲਤ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗੀ।',
        tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      },
      duty: {
        scheduleNotSet: 'ਸ਼ਡਿਊਲ ਤੈਅ ਨਹੀਂ ਹੈ',
        loadFailed: 'ਤੁਹਾਡੀ ਡਿਊਟੀ ਜਾਣਕਾਰੀ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀ।',
        updateFailed: 'ਡਿਊਟੀ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ',
        loading: 'ਡਿਊਟੀ ਡੈਸ਼ਬੋਰਡ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
        clockIn: 'ਕਲਾਕ ਇਨ',
        clockOut: 'ਕਲਾਕ ਆਉਟ',
        onDuty: 'ਡਿਊਟੀ ਉੱਤੇ',
        offDuty: 'ਆਫ ਡਿਊਟੀ',
        updating: 'ਅੱਪਡੇਟ ਹੋ ਰਿਹਾ ਹੈ…',
        tapToClockIn: 'ਕਲਾਕ ਇਨ ਲਈ ਟੈਪ ਕਰੋ',
        tapToClockOut: 'ਕਲਾਕ ਆਉਟ ਲਈ ਟੈਪ ਕਰੋ',
        statusActive: 'ਤੁਹਾਡੀ ਡਿਊਟੀ ਸਥਿਤੀ ਸਰਗਰਮ ਹੈ',
        statusAvailable: 'ਤੁਹਾਡੀ ਏਜੰਸੀ ਤੁਹਾਨੂੰ ਉਪਲਬਧ ਦੇਖੇਗੀ',
        currentAssignment: 'ਮੌਜੂਦਾ ਅਸਾਈਨਮੈਂਟ',
        radioContact: 'ਰੇਡੀਓ ਸੰਪਰਕ',
        photoLogTitle: 'ਅੱਜ ਦਾ ਫੋਟੋ ਲੌਗ',
        assignmentDetails: 'ਅਸਾਈਨਮੈਂਟ ਵੇਰਵੇ',
        callControlRoom: 'ਕੰਟਰੋਲ ਰੂਮ ਨੂੰ ਕਾਲ ਕਰੋ',
        photoLog: 'ਫੋਟੋ ਲੌਗ',
        noSiteAssigned: 'ਕੋਈ ਸਾਈਟ ਨਹੀਂ ਲਗਾਈ',
        noActiveSite: 'ਕੋਈ ਸਰਗਰਮ ਸਾਈਟ ਨਹੀਂ ਲਗਾਈ',
        active: 'ਸਰਗਰਮ',
        assigned: 'ਲਗਾਈ ਗਈ',
        controlRoom: 'ਕੰਟਰੋਲ ਰੂਮ ਸਹਾਇਤਾ',
        channel: 'ਚੈਨਲ 1 · 24×7 ਸਹਾਇਤਾ',
        photoEmpty: 'ਅੱਜ ਦਾ ਫੋਟੋ ਲੌਗ ਖਾਲੀ ਹੈ',
        photoEmptyHint: 'ਆਪਣੀ ਸ਼ਿਫਟ ਦੌਰਾਨ ਸਾਈਟ ਦੀਆਂ ਫੋਟੋਆਂ ਲਵੋ',
        salaryTitle: 'ਤਨਖ਼ਾਹ',
        salaryRow: 'ਤਨਖ਼ਾਹ ਅਤੇ ਪੇ-ਸਲਿਪ',
        salaryCaption: 'ਇਤਿਹਾਸ ਅਤੇ ਐਡਵਾਂਸ ਵੇਖੋ',
      },
      patrol: {
        loadFailed: 'ਗਸ਼ਤ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
        loading: 'ਗਸ਼ਤ ਡੈਸ਼ਬੋਰਡ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
        completedTitle: 'ਗਸ਼ਤ ਪੂਰੀ ਹੋਈ',
        completedBody: 'ਸਾਰੇ ਚੈੱਕਪੁਆਇੰਟ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋ ਗਏ ਹਨ।',
        updateFailed: 'ਗਸ਼ਤ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ',
        updating: 'ਗਸ਼ਤ ਅੱਪਡੇਟ ਹੋ ਰਹੀ ਹੈ…',
        scanCheckpoint: 'ਚੈੱਕਪੁਆਇੰਟ ਸਕੈਨ ਕਰੋ',
        startPatrol: 'ਗਸ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
        scanNext: 'ਅਗਲਾ ਚੈੱਕਪੁਆਇੰਟ ਸਕੈਨ ਕਰੋ',
        startAction: 'ਗਸ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
        recordNext: 'ਅਗਲਾ ਗਸ਼ਤ ਚੈੱਕਪੁਆਇੰਟ ਦਰਜ ਕਰੋ',
        beginRoute: 'ਆਪਣਾ ਨਿਰਧਾਰਤ ਚੈੱਕਪੁਆਇੰਟ ਰੂਟ ਸ਼ੁਰੂ ਕਰੋ',
        noCheckpoints: 'ਕੋਈ ਚੈੱਕਪੁਆਇੰਟ ਨਹੀਂ ਲਗਾਇਆ',
        progress: 'ਗਸ਼ਤ ਪ੍ਰਗਤੀ',
        completedCount: '{{scanned}}/{{total}} ਪੂਰੇ ਹੋਏ',
        nextCheckpoint: 'ਅਗਲਾ ਚੈੱਕਪੁਆਇੰਟ',
        nextCheckpointHint: 'ਤੁਹਾਡੇ ਰੂਟ ਦਾ ਅਗਲਾ ਚੈੱਕਪੁਆਇੰਟ',
        recentScans: 'ਹਾਲ ਦੇ ਸਕੈਨ',
        noScansYet: 'ਅੱਜ ਹਾਲੇ ਕੋਈ ਚੈੱਕਪੁਆਇੰਟ ਸਕੈਨ ਨਹੀਂ ਹੋਇਆ।',
        checkpointList: 'ਚੈੱਕਪੁਆਇੰਟ ਸੂਚੀ',
        checkpointListWithSite: 'ਚੈੱਕਪੁਆਇੰਟ ਸੂਚੀ — {{site}}',
        checkpointCount: '{{count}} ਚੈੱਕਪੁਆਇੰਟ',
        allScanned: 'ਸਾਰੇ ਚੈੱਕਪੁਆਇੰਟ ਸਕੈਨ ਹੋ ਗਏ',
        roundCompletedTitle: 'ਗਸ਼ਤ ਰਾਊਂਡ ਪੂਰਾ ਹੋਇਆ',
        roundCompletedBody: 'ਧੰਨਵਾਦ — ਪੂਰਾ ਰੂਟ ਦਰਜ ਹੋ ਗਿਆ ਹੈ।',
      },
      report: {
        severityLow: 'ਘੱਟ',
        severityMedium: 'ਦਰਮਿਆਨਾ',
        severityHigh: 'ਉੱਚ',
        describeTitle: 'ਘਟਨਾ ਦਾ ਵੇਰਵਾ ਦਿਓ',
        describeBody: 'ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਘਟਨਾ, ਥਾਂ ਅਤੇ ਕੀਤੀ ਕਾਰਵਾਈ ਲਿਖੋ।',
        submittedTitle: 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਹੋ ਗਈ',
        submittedBody: 'ਤੁਹਾਡੀ ਏਜੰਸੀ ਨੂੰ ਇਸ ਘਟਨਾ ਬਾਰੇ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।',
        submitFailed: 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਨਹੀਂ ਹੋ ਸਕੀ',
        reportDetails: 'ਰਿਪੋਰਟ ਵੇਰਵੇ',
        severity: 'ਗੰਭੀਰਤਾ',
        whatHappened: 'ਕੀ ਹੋਇਆ',
        notesPlaceholder: 'ਘਟਨਾ, ਥਾਂ ਅਤੇ ਕੀਤੀ ਕਾਰਵਾਈ ਲਿਖੋ…',
        incidentDetails: 'ਘਟਨਾ ਦੇ ਵੇਰਵੇ',
        attachments: 'ਅਟੈਚਮੈਂਟ',
        photoTitle: 'ਫੋਟੋ ਅਟੈਚਮੈਂਟ',
        photoBody: 'ਐਪ ਕੈਮਰਾ ਜਾਂ ਗੈਲਰੀ ਪਿਕਰ ਜੁੜਨ ਤੇ ਫੋਟੋ ਅਟੈਚਮੈਂਟ ਚਾਲੂ ਹੋਵੇਗਾ।',
        attachPhoto: 'ਫੋਟੋ ਲਗਾਓ',
        submitReport: 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ',
        submitting: 'ਜਮ੍ਹਾਂ ਹੋ ਰਹੀ ਹੈ…',
      },
      salary: {
        headerTitle: 'ਤਨਖ਼ਾਹ',
        totalSalary: 'ਕੁੱਲ ਤਨਖ਼ਾਹ',
        pending: 'ਬਾਕੀ',
        verified: 'ਸਤਿਆਪਿਤ',
        basicSalary: 'ਮੁੱਢਲੀ ਤਨਖ਼ਾਹ',
        overtime: 'ਓਵਰਟਾਈਮ',
        allowances: 'ਭੱਤੇ',
        deductions: 'ਕਟੌਤੀ',
        netSalary: 'ਨੈੱਟ ਤਨਖ਼ਾਹ',
        downloadPayslip: 'ਪੇ-ਸਲਿਪ ਡਾਊਨਲੋਡ ਕਰੋ',
        payslipSoon: 'ਪੇ-ਸਲਿਪ ਡਾਊਨਲੋਡ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗਾ।',
        history: 'ਤਨਖ਼ਾਹ ਇਤਿਹਾਸ',
        advanceHistory: 'ਐਡਵਾਂਸ ਅਤੇ ਕਟੌਤੀ ਇਤਿਹਾਸ',
        noAdvances: 'ਕੋਈ ਬਾਕੀ ਐਡਵਾਂਸ ਨਹੀਂ।',
        loading: 'ਤਨਖ਼ਾਹ ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
        loadFailed: 'ਤਨਖ਼ਾਹ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
        retry: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      },
    },
    invoice: {
      sendInvoice: 'ਇਨਵੌਇਸ ਭੇਜੋ',
      invoicesSent: 'ਭੇਜੇ ਗਏ ਇਨਵੌਇਸ',
      selectClient: 'ਕਲਾਇੰਟ ਚੁਣੋ',
      amount: 'ਰਕਮ',
      amountPlaceholder: 'ਰਕਮ ਦਰਜ ਕਰੋ',
      description: 'ਵੇਰਵਾ',
      descriptionPlaceholder: 'ਵੇਰਵਾ ਦਰਜ ਕਰੋ',
      dueDate: 'ਦੇਣ ਦੀ ਮਿਤੀ',
      dueDatePlaceholder: 'dd/mm/yyyy',
      selectDueDate: 'ਦੇਣ ਦੀ ਮਿਤੀ ਚੁਣੋ',
      send: 'ਇਨਵੌਇਸ ਭੇਜੋ',
      sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      required: 'ਕਲਾਇੰਟ, ਰਕਮ ਅਤੇ ਦੇਣ ਦੀ ਮਿਤੀ ਚੁਣੋ।',
      invalidAmount: 'ਸਿਫ਼ਰ ਤੋਂ ਵੱਧ ਵੈਧ ਰਕਮ ਦਰਜ ਕਰੋ।',
      sent: '{{client}} ਨੂੰ ਇਨਵੌਇਸ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।',
      sendFailed: 'ਇਨਵੌਇਸ ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ।',
      loadingClients: 'ਕਲਾਇੰਟ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
      noClients: 'ਹਾਲੇ ਕੋਈ ਕਲਾਇੰਟ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      noClientsHint: 'ਕਵਰੇਜ ਬੇਨਤੀਆਂ ਆਉਣ ਤੇ ਕਲਾਇੰਟ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
      noInvoices: 'ਹਾਲੇ ਤੱਕ ਕੋਈ ਇਨਵੌਇਸ ਨਹੀਂ ਭੇਜਿਆ ਗਿਆ।',
      pending: 'ਬਾਕੀ',
      paid: 'ਭੁਗਤਾਨ ਕੀਤਾ ਗਿਆ',
      guardsAssigned: 'ਤੈਨਾਤ ਗਾਰਡ',
      totalSalary: 'ਕੁੱਲ ਤਨਖ਼ਾਹ',
      noGuards: 'ਇਸ ਕਲਾਇੰਟ ਸਾਈਟ ਤੇ ਹਾਲੇ ਕੋਈ ਗਾਰਡ ਤੈਨਾਤ ਨਹੀਂ ਹੈ।',
      addOn: 'ਐਡ ਆਨ',
      add1000: '+1000',
      add2000: '+2000',
      addCustom: '+ਕਸਟਮ',
      customAddOn: 'ਕਸਟਮ ਐਡ ਆਨ',
      apply: 'ਲਾਗੂ ਕਰੋ',
      removeAddOn: 'ਐਡ ਆਨ ਹਟਾਓ',
    },
  },
};

export default pa;
