const pa = {
  translation: {
    addGuardForm: {
      title: 'ਗਾਰਡ ਜੋੜੋ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      email: 'ਈਮੇਲ',
      password: 'ਪਾਸਵਰਡ',
      joiningDate: 'ਨਿਯੁਕਤੀ ਦੀ ਮਿਤੀ',
      address: 'ਪਤਾ (ਵਿਕਲਪਿਕ)',
      age: 'ਉਮਰ (ਵਿਕਲਪਿਕ)',
      gender: 'ਲਿੰਗ (ਵਿਕਲਪਿਕ)',
      male: 'ਮਰਦ',
      female: 'ਔਰਤ',
      other: 'ਹੋਰ',
      site: 'ਸ਼ੁਰੂਆਤੀ ਸਾਈਟ ਨਿਯੁਕਤੀ',
      unassigned: 'ਅਣਨਿਯੁਕਤ',
      loadingSites: 'ਸਾਈਟਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      siteError:
        'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋਈਆਂ। ਬਿਨਾਂ ਸਾਈਟ ਗਾਰਡ ਜੋੜੋ ਜਾਂ ਫਾਰਮ ਮੁੜ ਖੋਲ੍ਹੋ।',
      coveragePlan: 'ਕਵਰੇਜ ਯੋਜਨਾ',
      day_shift: 'ਦਿਨ ਦੀ ਸ਼ਿਫਟ',
      night_watch: 'ਰਾਤ ਦੀ ਸ਼ਿਫਟ',
      '24x7': '24×7 ਕਵਰੇਜ',
      shiftHours: 'ਸ਼ਿਫਟ ਦੀ ਮਿਆਦ',
      hours: 'ਘੰਟੇ',
      startTime: 'ਸ਼ੁਰੂ ਸਮਾਂ',
      endTime: 'ਸਮਾਪਤੀ ਸਮਾਂ',
      endHint:
        'ਸਮਾਪਤੀ ਸਮਾਂ ਚੁਣੀ ਮਿਆਦ ਅਨੁਸਾਰ ਨਿਰਧਾਰਤ ਹੁੰਦਾ ਹੈ, ਰਾਤ ਦੀ ਸ਼ਿਫਟ ਸਮੇਤ।',
      coverageHint:
        '24×7 ਕਵਰੇਜ ਵਾਰੀ-ਵਾਰੀ ਸ਼ਿਫਟਾਂ ਵਰਤਦੀ ਹੈ; ਇੱਥੇ ਵੱਖਰੀ ਸ਼ਿਫਟ ਮਿਆਦ ਨਹੀਂ ਦਿੱਤੀ ਜਾਂਦੀ।',
      basicSalary: 'ਮੂਲ ਤਨਖਾਹ (ਵਿਕਲਪਿਕ)',
      allowances: 'ਭੱਤੇ (ਵਿਕਲਪਿਕ)',
      requiredHint: '* ਵਾਲੇ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹਨ।',
      requiredError: 'ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      contactError:
        'ਵੈਧ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ, ਈਮੇਲ ਅਤੇ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ।',
      dateError: 'ਵੈਧ ਮਿਤੀ YYYY-MM-DD ਵਿੱਚ ਦਰਜ ਕਰੋ।',
      ageError: 'ਉਮਰ 18 ਤੋਂ 65 ਵਿਚਕਾਰ ਪੂਰਾ ਅੰਕ ਹੋਵੇ।',
      salaryError: 'ਤਨਖਾਹ ਅਤੇ ਭੱਤੇ ਸਿਫ਼ਰ ਜਾਂ ਵੱਧ, ਦੋ ਦਸ਼ਮਲਵ ਅੰਕਾਂ ਤੱਕ ਦਰਜ ਕਰੋ।',
      success: 'ਗਾਰਡ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ।',
      failure: 'ਗਾਰਡ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      search: 'ਵਿਕਲਪ ਖੋਜੋ',
      noResults: 'ਕੋਈ ਵਿਕਲਪ ਨਹੀਂ ਮਿਲਿਆ।',
      close: 'ਬੰਦ ਕਰੋ',
    },
    common: {
      next: 'ਅੱਗੇ',
      back: 'ਵਾਪਸ',
      continue: 'ਜਾਰੀ ਰੱਖੋ',
      getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    },

    auth: {
      welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
      login: 'ਲਾਗ ਇਨ',
      createAccount: 'ਖਾਤਾ ਬਣਾਓ',
      forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?',
      enterValidIdentifier: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      couldNotSendOtp: 'OTP ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ',
      identifierPlaceholder: 'ਈਮੇਲ ਜਾਂ +91 ਮੋਬਾਈਲ ਨੰਬਰ',
      passwordChanged: 'ਤੁਹਾਡਾ ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲਿਆ ਗਿਆ ਹੈ।',
      invalidOtp: 'ਗਲਤ OTP',
      completeOtp: 'ਪੂਰਾ 6 ਅੰਕਾਂ ਦਾ ਪੁਸ਼ਟੀ ਕੋਡ ਦਰਜ ਕਰੋ।',
      verificationFailed: 'ਪੁਸ਼ਟੀ ਅਸਫਲ',
      identifierFallback: 'ਤੁਹਾਡਾ ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ',
      otpDigit: 'OTP ਅੰਕ {{number}}',
      mobileOtpDigit: 'ਮੋਬਾਈਲ ਪੁਸ਼ਟੀ ਅੰਕ {{number}}',
      loginSubtitle: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਲਾਗ ਇਨ ਕਰੋ',
      emailAddress: 'ਈਮੇਲ ਪਤਾ',
      password: 'ਪਾਸਵਰਡ',
      enterPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      showPassword: 'ਪਾਸਵਰਡ ਦਿਖਾਓ',
      hidePassword: 'ਪਾਸਵਰਡ ਲੁਕਾਓ',
      loggingIn: 'ਲਾਗ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
      orContinueWith: 'ਜਾਂ ਇਸ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      signUp: 'ਸਾਈਨ ਅੱਪ ਕਰੋ',
      invalidDetails: 'ਗਲਤ ਜਾਣਕਾਰੀ',
      enterLinkedEmail: 'ਆਪਣੇ ਖਾਤੇ ਨਾਲ ਜੁੜਿਆ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      invalidPassword: 'ਗਲਤ ਪਾਸਵਰਡ',
      loginFailed: 'ਲਾਗ ਇਨ ਅਸਫਲ',
      tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      createSubtitle: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਜਾਣਕਾਰੀ ਭਰੋ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      exampleName: 'ਜਿਵੇਂ ਆਕਾਸ਼ ਸਿੰਘ',
      alreadyAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
      invalidName: 'ਗਲਤ ਨਾਮ',
      enterFullName: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      invalidEmail: 'ਗਲਤ ਈਮੇਲ ਪਤਾ',
      enterValidEmail: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      passwordsMismatch: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
      passwordsMismatchMessage: 'ਪਾਸਵਰਡ ਅਤੇ ਪੁਸ਼ਟੀ ਇੱਕੋ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
      accountFailed: 'ਖਾਤਾ ਨਹੀਂ ਬਣ ਸਕਿਆ',
      backToSuperAdmin: 'ਸੁਪਰ ਐਡਮਿਨ ਵੱਲ ਵਾਪਸ',
      goBack: 'ਵਾਪਸ ਜਾਓ',
      forgotTitle: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
      emailOrMobile: 'ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ',
      rememberPassword: 'ਪਾਸਵਰਡ ਯਾਦ ਹੈ?',
      sendOtp: 'OTP ਭੇਜੋ',
      sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      forgotSubtitle: 'ਆਪਣਾ ਰਜਿਸਟਰਡ ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      verifyMobile: 'ਮੋਬਾਈਲ ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      verifyOtp: 'OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      enterCodeSent: 'ਭੇਜਿਆ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
      didNotReceive: 'OTP ਨਹੀਂ ਮਿਲਿਆ?',
      resendOtp: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      resendIn: '00:30 ਵਿੱਚ',
      verifyContinue: 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ',
      verifying: 'ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ...',
      couldNotResend: 'OTP ਦੁਬਾਰਾ ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ',
      newPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ',
      enterNewPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      confirmNewPassword: 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      newPasswordSubtitle: 'ਆਪਣਾ ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      resetPassword: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
      resetting: 'ਰੀਸੈੱਟ ਹੋ ਰਿਹਾ ਹੈ...',
      passwordUpdated: 'ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਇਆ!',
      passwordUpdatedMessage:
        'ਤੁਹਾਡਾ ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਹੋ ਗਿਆ ਹੈ। ਹੁਣ ਨਵੇਂ ਪਾਸਵਰਡ ਨਾਲ ਲਾਗ ਇਨ ਕਰੋ।',
      goToLogin: 'ਲਾਗ ਇਨ ਤੇ ਜਾਓ',
      invalidMobile: 'ਗਲਤ ਮੋਬਾਈਲ ਨੰਬਰ',
      enterValidMobile: 'ਸਹੀ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      confirmMustMatch: 'ਪੁਸ਼ਟੀ ਪਾਸਵਰਡ ਨਾਲ ਮਿਲਣੀ ਚਾਹੀਦੀ ਹੈ।',
      accountType: 'ਖਾਤਾ ਕਿਸਮ',
      chooseAccountType: 'ਆਪਣੀ ਖਾਤਾ ਕਿਸਮ ਚੁਣੋ...',
      agency: 'ਏਜੰਸੀ',
      client: 'ਕਲਾਇੰਟ',
      agencyDescription: 'ਗਾਰਡ ਅਤੇ ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ\nਸੰਭਾਲੋ',
      clientDescription: 'ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ ਲਵੋ ਅਤੇ\nਸੰਭਾਲੋ',
      creatingAccount: 'ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    },
    onboarding: {
      step1: {
        title: 'ਲੋਕ ਸੁਰੱਖਿਅਤ,\nਥਾਵਾਂ ਸੁਰੱਖਿਅਤ।',
        subtitle: 'ਪੇਸ਼ੇਵਰ ਸੁਰੱਖਿਆ ਪ੍ਰਬੰਧਨ ਹੁਣ ਸਰਲ, ਭਰੋਸੇਯੋਗ ਅਤੇ ਕੁਸ਼ਲ।',
      },
      step2: {
        title: 'ਕਦੇ ਵੀ, ਕਿਤੇ ਵੀ ਪ੍ਰਬੰਧ ਕਰੋ',
        subtitle: 'ਤੁਸੀਂ ਜਿੱਥੇ ਵੀ ਹੋਵੋ, ਆਪਣੇ ਸੁਰੱਖਿਆ ਕਾਰਜਾਂ ਨਾਲ ਜੁੜੇ ਰਹੋ।',
      },
      step3: {
        title: 'ਸੁਚੇਤ ਰਹੋ, ਤੇਜ਼ੀ ਨਾਲ ਜਵਾਬ ਦਿਓ।',
        subtitle: 'ਅੱਪਡੇਟ ਲਵੋ ਅਤੇ ਘਟਨਾਵਾਂ ਦਾ ਬਿਨਾਂ ਦੇਰੀ ਜਵਾਬ ਦਿਓ।',
      },
    },
    superAdmin: {
      agencies: 'ਏਜੰਸੀਆਂ',
      approvals: 'ਮਨਜ਼ੂਰੀਆਂ',
      liveStatus: 'ਲਾਈਵ ਸਥਿਤੀ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      addAgency: 'ਨਵੀਂ ਏਜੰਸੀ ਜੋੜੋ',
      searchAgencies: 'ਨਾਮ ਨਾਲ ਏਜੰਸੀ ਖੋਜੋ',
      active: 'ਸਰਗਰਮ',
      inactive: 'ਗੈਰ-ਸਰਗਰਮ',
      guards: 'ਗਾਰਡ',
      clients: 'ਕਲਾਇੰਟ',
      loadingAgencies: 'ਏਜੰਸੀਆਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ',
      unableAgencies: 'ਏਜੰਸੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      noMatching: 'ਕੋਈ ਮਿਲਦੀ ਏਜੰਸੀ ਨਹੀਂ',
      noInactive: 'ਕੋਈ ਗੈਰ-ਸਰਗਰਮ ਏਜੰਸੀ ਨਹੀਂ',
      noActive: 'ਹਾਲੇ ਕੋਈ ਸਰਗਰਮ ਏਜੰਸੀ ਨਹੀਂ',
      searchHint: 'ਹੋਰ ਏਜੰਸੀ ਨਾਮ ਖੋਜੋ ਜਾਂ ਸਥਿਤੀ ਫਿਲਟਰ ਬਦਲੋ।',
      approvalHint: 'ਮਨਜ਼ੂਰ ਏਜੰਸੀਆਂ ਸੁਪਰ ਐਡਮਿਨ ਸਮੀਖਿਆ ਤੋਂ ਬਾਅਦ ਇੱਥੇ ਦਿਖਣਗੀਆਂ।',
      networkTitle: 'ਤੁਹਾਡਾ ਨੈੱਟਵਰਕ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ',
      liveUnavailable: 'ਲਾਈਵ ਰਿਪੋਰਟਿੰਗ ਹਾਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      agencyApprovals: 'ਏਜੰਸੀ ਮਨਜ਼ੂਰੀਆਂ',
      refreshRequests: 'ਬੇਨਤੀਆਂ ਤਾਜ਼ਾ ਕਰੋ',
      noPending: 'ਕੋਈ ਏਜੰਸੀ ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਵਿੱਚ ਨਹੀਂ ਹੈ।',
      approve: 'ਮਨਜ਼ੂਰ ਕਰੋ',
      reject: 'ਰੱਦ ਕਰੋ',
      notifications: 'ਸੂਚਨਾਵਾਂ',
      markAllRead: 'ਸਭ ਪੜ੍ਹੀਆਂ ਕਰੋ',
      reviewApprovals: 'ਏਜੰਸੀ ਮਨਜ਼ੂਰੀਆਂ ਵੇਖੋ',
      loadingNotifications: 'ਸੂਚਨਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      tryAgain: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      noNotifications: 'ਹਾਲੇ ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ',
      deleteNotification: 'ਸੂਚਨਾ ਹਟਾਉਣੀ ਹੈ?',
      deleteNotificationMessage: 'ਇਹ ਸੂਚਨਾ ਹਟਾ ਦਿੱਤੀ ਜਾਵੇਗੀ।',
      delete: 'ਹਟਾਓ',
      cancel: 'ਰੱਦ ਕਰੋ',
      loadingProfile: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…',
      profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
      photoSoon: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅੱਪਲੋਡ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗਾ।',
      yourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ',
      accountId: 'ਖਾਤਾ ਆਈਡੀ: {{id}}',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      email: 'ਈਮੇਲ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      saveChanges: 'ਬਦਲਾਅ ਸੰਭਾਲੋ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profileUpdated: 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਹੋਈ',
      changesSaved: 'ਤੁਹਾਡੇ ਬਦਲਾਅ ਸੰਭਾਲੇ ਗਏ ਹਨ।',
      fullNameRequired: 'ਪੂਰਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterFullName: 'ਸੁਪਰ ਐਡਮਿਨ ਦਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      invalidEmail: 'ਗਲਤ ਈਮੇਲ',
      enterEmail: 'ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      invalidPhone: 'ਗਲਤ ਫੋਨ ਨੰਬਰ',
      enterPhone: 'ਸਹੀ 10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      editAgency: 'ਏਜੰਸੀ ਸੋਧੋ',
      manageAgency: 'ਏਜੰਸੀ ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ ਸੰਭਾਲੋ',
      agencyDetails: 'ਏਜੰਸੀ ਵੇਰਵੇ',
      accountDetails: 'ਖਾਤਾ ਵੇਰਵੇ',
      businessDetails: 'ਕਾਰੋਬਾਰੀ ਵੇਰਵੇ',
      address: 'ਪਤਾ',
      status: 'ਸਥਿਤੀ',
      leavePassword: 'ਮੌਜੂਦਾ ਰੱਖਣ ਲਈ ਖਾਲੀ ਛੱਡੋ',
      removeAgency: 'ਏਜੰਸੀ ਹਟਾਓ',
      agencyUpdated: 'ਏਜੰਸੀ ਅੱਪਡੇਟ ਹੋਈ',
      agencySaved: 'ਏਜੰਸੀ ਦੀ ਜਾਣਕਾਰੀ ਸੰਭਾਲੀ ਗਈ ਹੈ।',
      loadingLocations: 'ਥਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      closeEditor: 'ਏਜੰਸੀ ਸੋਧਕ ਬੰਦ ਕਰੋ',
    },
    details: {
      agencyTitle: 'ਏਜੰਸੀ ਵੇਰਵੇ',
      agencySubtitle: 'ਆਪਣੀ ਏਜੰਸੀ ਬਾਰੇ ਦੱਸੋ',
      agencyName: 'ਏਜੰਸੀ / ਕੰਪਨੀ ਦਾ ਨਾਮ',
      enterAgencyName: 'ਏਜੰਸੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      businessType: 'ਕਾਰੋਬਾਰ ਦੀ ਕਿਸਮ',
      gstNumber: 'GST ਨੰਬਰ (ਵਿਕਲਪਿਕ)',
      enterGst: 'GST ਨੰਬਰ ਦਰਜ ਕਰੋ',
      officeAddress: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ',
      enterOfficeAddress: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      clientTitle: 'ਕਲਾਇੰਟ ਵੇਰਵੇ',
      clientSubtitle: 'ਆਪਣੀ ਸੰਸਥਾ ਬਾਰੇ ਦੱਸੋ',
      companyName: 'ਕੰਪਨੀ / ਸੰਸਥਾ ਦਾ ਨਾਮ',
      enterCompanyName: 'ਕੰਪਨੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteName: 'ਸਾਈਟ / ਜਾਇਦਾਦ ਦਾ ਨਾਮ',
      enterSiteName: 'ਸਾਈਟ/ਜਾਇਦਾਦ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ',
      enterSiteAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      enterCity: 'ਸ਼ਹਿਰ ਦਰਜ ਕਰੋ',
      selectState: 'ਰਾਜ ਚੁਣੋ',
      enterPincode: 'ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ',
      loadingLocations: 'ਥਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ…',
      closeLocations: 'ਥਾਂ ਵਿਕਲਪ ਬੰਦ ਕਰੋ',
      agencyNameRequired: 'ਏਜੰਸੀ ਦਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterAgencyCompany: 'ਆਪਣੀ ਏਜੰਸੀ ਜਾਂ ਕੰਪਨੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      businessRequired: 'ਕਾਰੋਬਾਰ ਕਿਸਮ ਲਾਜ਼ਮੀ ਹੈ',
      selectBusiness: 'ਆਪਣੀ ਕਾਰੋਬਾਰ ਕਿਸਮ ਚੁਣੋ।',
      officeRequired: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
      enterOffice: 'ਦਫ਼ਤਰ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ।',
      cityRequired: 'ਸ਼ਹਿਰ ਲਾਜ਼ਮੀ ਹੈ',
      enterYourCity: 'ਆਪਣਾ ਸ਼ਹਿਰ ਦਰਜ ਕਰੋ।',
      stateRequired: 'ਰਾਜ ਲਾਜ਼ਮੀ ਹੈ',
      selectStateTerritory: 'ਆਪਣਾ ਰਾਜ ਜਾਂ ਕੇਂਦਰ ਸ਼ਾਸਿਤ ਪ੍ਰਦੇਸ਼ ਚੁਣੋ।',
      districtRequired: 'ਜ਼ਿਲ੍ਹਾ ਲਾਜ਼ਮੀ ਹੈ',
      selectDistrict: 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ।',
      invalidPincode: 'ਗਲਤ ਪਿੰਨਕੋਡ',
      enterValidPincode: 'ਸਹੀ 6 ਅੰਕਾਂ ਦਾ ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ।',
      siteNameRequired: 'ਸਾਈਟ ਦਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      enterProperty: 'ਆਪਣੀ ਸਾਈਟ ਜਾਂ ਜਾਇਦਾਦ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      siteAddressRequired: 'ਸਾਈਟ ਦਾ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
      enterAddress: 'ਸਾਈਟ ਦਾ ਪਤਾ ਦਰਜ ਕਰੋ।',
    },
    client: {
      home: 'ਹੋਮ',
      request: 'ਬੇਨਤੀ',
      invoices: 'ਇਨਵੌਇਸ',
      alerts: 'ਅਲਰਟ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      portal: 'ਕਲਾਇੰਟ ਪੋਰਟਲ',
      loading: 'ਕਲਾਇੰਟ ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
      loadFailed: 'ਕਲਾਇੰਟ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      yourAgencies: 'ਤੁਹਾਡੀਆਂ ਏਜੰਸੀਆਂ',
      noAgency: 'ਕੋਈ ਏਜੰਸੀ ਨਿਯੁਕਤ ਨਹੀਂ ਹੈ',
      noAgencyHint: 'ਤੁਹਾਡੀ ਨਿਯੁਕਤ ਸੁਰੱਖਿਆ ਏਜੰਸੀ ਇੱਥੇ ਦਿਖੇਗੀ।',
      coveragePlan: 'ਕਵਰੇਜ ਯੋਜਨਾ',
      noCoverage: 'ਕੋਈ ਕਵਰੇਜ ਯੋਜਨਾ ਨਹੀਂ',
      noCoverageHint: 'ਏਜੰਸੀ ਨਿਯੁਕਤ ਹੋਣ ਤੇ ਕਵਰੇਜ ਵੇਰਵੇ ਇੱਥੇ ਦਿਖਣਗੇ।',
      requestCoverage: 'ਸੁਰੱਖਿਆ ਕਵਰੇਜ ਦੀ ਬੇਨਤੀ ਕਰੋ',
      requestHint: 'ਕਵਰੇਜ ਬੇਨਤੀ ਸਹੂਲਤ ਇੱਥੇ ਦਿਖੇਗੀ।',
      noInvoices: 'ਕੋਈ ਇਨਵੌਇਸ ਨਹੀਂ',
      noInvoicesHint: 'ਉਪਲਬਧ ਹੋਣ ਤੇ ਤੁਹਾਡੇ ਇਨਵੌਇਸ ਇੱਥੇ ਦਿਖਣਗੇ।',
      noAlerts: 'ਕੋਈ ਅਲਰਟ ਨਹੀਂ',
      noAlertsHint: 'ਸੁਰੱਖਿਆ ਅਤੇ ਖਾਤਾ ਅਲਰਟ ਇੱਥੇ ਦਿਖਣਗੇ।',
    },
    coverageRequest: {
      location: 'ਤੁਹਾਡੀ ਥਾਂ',
      eventName: 'ਸਮਾਗਮ ਦਾ ਨਾਮ',
      eventPlaceholder: 'ਸਮਾਗਮ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      siteLocation: 'ਸਾਈਟ ਜਾਂ ਸਮਾਗਮ ਦੀ ਥਾਂ',
      sitePlaceholder: 'ਜਿਵੇਂ ਈਸਟ ਵਿੰਗ ਦਾਖਲਾ',
      guardsNeeded: 'ਲੋੜੀਂਦੇ ਗਾਰਡ',
      notes: 'ਨੋਟਸ',
      notesPlaceholder: 'ਮਿਤੀਆਂ, ਸ਼ਿਫਟ ਸਮਾਂ, ਖਾਸ ਲੋੜਾਂ…',
      send: 'ਬੇਨਤੀ ਭੇਜੋ',
      sending: 'ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ…',
      myRequests: 'ਮੇਰੀਆਂ ਬੇਨਤੀਆਂ',
      none: 'ਹਾਲੇ ਕੋਈ ਕਵਰੇਜ ਬੇਨਤੀ ਨਹੀਂ ਹੈ।',
      required: 'ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      sentTitle: 'ਬੇਨਤੀ ਭੇਜੀ ਗਈ',
      sentMessage: 'ਤੁਹਾਡੀ ਕਵਰੇਜ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਹੋ ਗਈ ਹੈ।',
      sendFailed: 'ਬੇਨਤੀ ਨਹੀਂ ਭੇਜੀ ਜਾ ਸਕੀ।',
      loadFailed: 'ਬੇਨਤੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      locationFailed: 'ਥਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      selectStateFirst: 'ਪਹਿਲਾਂ ਰਾਜ ਚੁਣੋ।',
      selectDistrictFirst: 'ਪਹਿਲਾਂ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ।',
      agenciesInArea: 'ਤੁਹਾਡੇ ਖੇਤਰ ਦੀਆਂ ਏਜੰਸੀਆਂ',
      noAgenciesInArea:
        'ਇਸ ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਅਜੇ ਕੋਈ ਏਜੰਸੀ ਨਹੀਂ ਮਿਲੀ — ਨੇੜਲਾ ਜ਼ਿਲ੍ਹਾ ਅਜ਼ਮਾਓ।',
      agenciesFailed: 'ਇਸ ਜ਼ਿਲ੍ਹੇ ਦੀਆਂ ਏਜੰਸੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      available: 'ਉਪਲਬਧ',
      selectAgency: 'ਚੁਣੋ',
      changeAgency: 'ਬਦਲੋ',
      status: {
        pending: 'ਲੰਬਿਤ',
        approved: 'ਮਨਜ਼ੂਰ',
        rejected: 'ਰੱਦ',
        assigned: 'ਨਿਯੁਕਤ',
        completed: 'ਪੂਰੀ',
        cancelled: 'ਰੱਦ ਕੀਤੀ',
      },
    },
    dashboard: {
      dashboard: 'ਡੈਸ਼ਬੋਰਡ',
      overview: 'ਓਵਰਵਿਊ',
      guard: 'ਗਾਰਡ',
      sites: 'ਸਾਈਟਾਂ',
      incidents: 'ਘਟਨਾਵਾਂ',
      plan: 'ਪਲਾਨ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      quickSummary: 'ਤੁਰੰਤ ਸੰਖੇਪ',
      today: 'ਅੱਜ',
      guardsOnDuty: 'ਡਿਊਟੀ ਉੱਤੇ ਗਾਰਡ',
      activeSites: 'ਸਰਗਰਮ ਸਾਈਟਾਂ',
      openIncidents: 'ਖੁੱਲ੍ਹੀਆਂ ਘਟਨਾਵਾਂ',
      unassignedGuards: 'ਨਾ ਲਗਾਏ ਗਾਰਡ',
      viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
      payrollSummary: 'ਪੇਰੋਲ ਸੰਖੇਪ',
      invoices: 'ਇਨਵੌਇਸ',
      clientReviews: 'ਕਲਾਇੰਟ ਸਮੀਖਿਆਵਾਂ',
      quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      liveStatus: 'ਲਾਈਵ ਸਥਿਤੀ',
      viewAll: 'ਸਾਰੇ ਵੇਖੋ',
      onDuty: 'ਡਿਊਟੀ ਉੱਤੇ',
      addGuard: '+ ਗਾਰਡ',
      addSite: '+ ਸਾਈਟ ਜੋੜੋ',
      incident: 'ਘਟਨਾ',
      fileIncident: 'ਘਟਨਾ ਦਰਜ ਕਰੋ',
      searchSites: 'ਸਾਈਟਾਂ ਖੋਜੋ...',
      filter: 'ਫਿਲਟਰ',
      loadingSites: 'ਸਾਈਟਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noSites: 'ਕੋਈ ਸਾਈਟ ਨਹੀਂ ਮਿਲੀ।',
      loadingIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
      noIncidents: 'ਕੋਈ ਘਟਨਾ ਨਹੀਂ ਮਿਲੀ।',
      unableToLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      unableToLoadIncidents: 'ਘਟਨਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      site: 'ਸਾਈਟ',
      selectSite: 'ਸਾਈਟ ਚੁਣੋ',
      selectInitialSite: 'ਸ਼ੁਰੂਆਤੀ ਸਾਈਟ ਚੁਣੋ',
      selectJoiningDate: 'ਨਿਯੁਕਤੀ ਦੀ ਮਿਤੀ ਚੁਣੋ',
      year: 'ਸਾਲ',
      month: 'ਮਹੀਨਾ',
      date: 'ਮਿਤੀ',
      done: 'ਹੋ ਗਿਆ',
      showPassword: 'ਪਾਸਵਰਡ ਦਿਖਾਓ',
      hidePassword: 'ਪਾਸਵਰਡ ਲੁਕਾਓ',
      previousMonth: 'ਪਿਛਲਾ ਮਹੀਨਾ',
      nextMonth: 'ਅਗਲਾ ਮਹੀਨਾ',
      editGuard: 'ਗਾਰਡ ਸੋਧੋ',
      guardUpdated: 'ਗਾਰਡ ਦੀ ਜਾਣਕਾਰੀ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਈ।',
      newGuardPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ (ਵਿਕਲਪਿਕ)',
      leavePasswordBlank: 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ ਰੱਖਣ ਲਈ ਖਾਲੀ ਛੱਡੋ',
      removeGuard: 'ਗਾਰਡ ਹਟਾਓ',
      removeGuardConfirmation:
        'ਇਸ ਗਾਰਡ ਨੂੰ ਹਟਾਉਣਾ ਹੈ? ਉਹਨਾਂ ਦਾ ਲੌਗਇਨ ਬੰਦ ਹੋ ਜਾਵੇਗਾ। ਇਹ ਵਾਪਸ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।',
      cancel: 'ਰੱਦ ਕਰੋ',
      all: 'ਸਾਰੇ',
      severity: 'ਗੰਭੀਰਤਾ',
      low: 'ਘੱਟ',
      medium: 'ਦਰਮਿਆਨਾ',
      high: 'ਉੱਚ',
      notes: 'ਨੋਟਸ',
      describeIncident: 'ਕੀ ਹੋਇਆ, ਵੇਰਵਾ ਦਿਓ...',
      uploadPhotos: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
      optional: '(ਵਿਕਲਪਿਕ)',
      addPhotos: 'ਫੋਟੋ ਜੋੜੋ',
      maxPhotos: 'ਵੱਧ ਤੋਂ ਵੱਧ 5 ਫੋਟੋਆਂ, ਹਰ ਇੱਕ 10MB ਤੱਕ',
      filing: 'ਦਰਜ ਹੋ ਰਿਹਾ ਹੈ...',
      incidentFiled: 'ਘਟਨਾ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋਈ',
      incidentRecorded: 'ਤੁਹਾਡੀ ਘਟਨਾ ਦਰਜ ਕਰ ਲਈ ਗਈ ਹੈ ਅਤੇ ਸਮੀਖਿਆ ਕੀਤੀ ਜਾਵੇਗੀ।',
      siteName: 'ਸਾਈਟ ਦਾ ਨਾਮ',
      address: 'ਪਤਾ',
      enterSiteName: 'ਸਾਈਟ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      enterCompleteAddress: 'ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ',
      startTyping: 'ਸੁਝਾਵਾਂ ਲਈ ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
      locationGps: 'ਟਿਕਾਣਾ (GPS)',
      noGps: 'ਕੋਈ GPS ਟਿਕਾਣਾ ਨਹੀਂ ਮਿਲਿਆ',
      useCurrentLocation: 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ ਵਰਤੋ',
      coveragePlan: 'ਕਵਰੇਜ ਪਲਾਨ',
      dayShift: 'ਦਿਨ ਦੀ ਸ਼ਿਫਟ',
      nightWatch: 'ਰਾਤ ਦੀ ਨਿਗਰਾਨੀ',
      coverage24x7: '24×7 ਕਵਰੇਜ',
      startTime: 'ਸ਼ੁਰੂਆਤੀ ਸਮਾਂ',
      endTime: 'ਅੰਤ ਸਮਾਂ',
      saveSite: 'ਸਾਈਟ ਸੇਵ ਕਰੋ',
      saving: 'ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ...',
      addressNotProvided: 'ਪਤਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      guardDataUnavailable: 'ਗਾਰਡ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
      notSet: 'ਸੈੱਟ ਨਹੀਂ ਹੈ',
      notScheduled: 'ਨਿਰਧਾਰਤ ਨਹੀਂ ਹੈ',
      myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      settings: 'ਸੈਟਿੰਗਾਂ',
      language: 'ਭਾਸ਼ਾ',
      appearance: 'ਦਿੱਖ',
      light: 'ਲਾਈਟ',
      dark: 'ਡਾਰਕ',
      system: 'ਸਿਸਟਮ',
      logOut: 'ਲੌਗ ਆਉਟ',
      english: 'ਅੰਗਰੇਜ਼ੀ',
      hindi: 'ਹਿੰਦੀ',
      punjabi: 'ਪੰਜਾਬੀ',
      missingDetails: 'ਵੇਰਵੇ ਅਧੂਰੇ ਹਨ',
      selectSiteAndDescribe: 'ਸਾਈਟ ਚੁਣੋ ਅਤੇ ਘਟਨਾ ਦਾ ਵੇਰਵਾ ਦਿਓ।',
      siteAndAddressRequired: 'ਸਾਈਟ ਦਾ ਨਾਮ ਅਤੇ ਪਤਾ ਲਾਜ਼ਮੀ ਹਨ।',
      couldNotFile: 'ਘਟਨਾ ਦਰਜ ਨਹੀਂ ਹੋ ਸਕੀ',
      couldNotLoadSites: 'ਸਾਈਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ',
      tryAgain: 'ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      photoUploadSoon: 'ਫੋਟੋ ਅੱਪਲੋਡ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
      gpsSoon: 'GPS ਟਿਕਾਣਾ ਸਹੂਲਤ ਜਲਦੀ ਜੋੜੀ ਜਾਵੇਗੀ।',
      close: 'ਬੰਦ ਕਰੋ',
      tapGuardDetails: 'ਗਾਰਡ ਦੇ ਵੇਰਵੇ ਦੇਖਣ ਜਾਂ ਸੋਧਣ ਲਈ ਟੈਪ ਕਰੋ',
      loadingGuards: 'ਗਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
      noGuardsOnDuty: 'ਇਸ ਵੇਲੇ ਕੋਈ ਗਾਰਡ ਡਿਊਟੀ ਉੱਤੇ ਨਹੀਂ ਹੈ।',
      unableToLoadGuards: 'ਗਾਰਡ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      unassignedSite: 'ਨਾ ਲਗਾਈ ਸਾਈਟ',
      live: 'ਲਾਈਵ',
      noLocationYet: 'ਹਾਲੇ ਕੋਈ ਟਿਕਾਣਾ ਨਹੀਂ',
      tapSiteManage: 'ਸਾਈਟਾਂ ਟੈਬ ਵਿੱਚ ਪ੍ਰਬੰਧਨ ਲਈ ਸਾਈਟ ਉੱਤੇ ਟੈਪ ਕਰੋ',
      active: 'ਸਰਗਰਮ',
      guardCount: '{{count}} ਗਾਰਡ',
      agencyAdmin: 'ਏਜੰਸੀ ਐਡਮਿਨ',
      accountDetails: 'ਖਾਤੇ ਦੇ ਵੇਰਵੇ',
      yourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
      emailAddress: 'ਈਮੇਲ ਪਤਾ',
      state: 'ਰਾਜ',
      district: 'ਜ਼ਿਲ੍ਹਾ',
      city: 'ਸ਼ਹਿਰ',
      pincode: 'ਪਿੰਨਕੋਡ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
      loadingProfile: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
      profileRequired: 'ਖਾਤੇ ਦੇ ਸਾਰੇ ਲਾਜ਼ਮੀ ਖੇਤਰ ਭਰੋ।',
      changesSaved: 'ਤੁਹਾਡੀਆਂ ਤਬਦੀਲੀਆਂ ਸੇਵ ਹੋ ਗਈਆਂ ਹਨ।',
      offlineAddressHint: 'ਆਫਲਾਈਨ ਹੋਣ ਤੇ ਪਤੇ ਦੇ ਸੁਝਾਅ ਉਪਲਬਧ ਨਹੀਂ ਹਨ।',
      rotateCoverage: '24 ਘੰਟਿਆਂ ਦੀ ਕਵਰੇਜ ਲਈ ਗਾਰਡ ਸ਼ਿਫਟਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।',
      selectedPlan: 'ਚੁਣਿਆ ਕਵਰੇਜ ਪਲਾਨ ਇਸ ਸਾਈਟ ਲਈ ਵਰਤਿਆ ਜਾਵੇਗਾ।',
      getDirections: 'ਦਿਸ਼ਾਵਾਂ ਲਵੋ',
      directionsUnavailable:
        'ਮੈਪ ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਜੁੜਨ ਤੋਂ ਬਾਅਦ ਦਿਸ਼ਾਵਾਂ ਉਪਲਬਧ ਹੋਣਗੀਆਂ।',
      removeSite: 'ਸਾਈਟ ਹਟਾਓ',
      siteUpdateUnavailable:
        'ਸਾਈਟ ਨੂੰ ਸੋਧਣ ਜਾਂ ਹਟਾਉਣ ਲਈ ਬੈਕਐਂਡ ਅਪਡੇਟ/ਡਿਲੀਟ ਐਂਡਪੌਇੰਟ ਦੀ ਲੋੜ ਹੈ।',
      searchGuards: 'ਨਾਮ, ਆਈਡੀ ਜਾਂ ਸਾਈਟ ਨਾਲ ਗਾਰਡ ਖੋਜੋ',
      offDuty: 'ਆਫ ਡਿਊਟੀ',
      noGuardsFound: 'ਕੋਈ ਗਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
      callGuard: 'ਗਾਰਡ ਨੂੰ ਕਾਲ ਕਰੋ',
      guardAddUnavailable: 'ਗਾਰਡ ਜੋੜਨ ਵਾਲਾ ਫਾਰਮ ਜਲਦੀ ਜੋੜਿਆ ਜਾਵੇਗਾ।',
      noMatchingLocations: 'ਕੋਈ ਮਿਲਦੀ ਥਾਂ ਨਹੀਂ ਮਿਲੀ।',
    },
  },
};

export default pa;
